package com.unique.mb.po;

import java.math.BigDecimal;
import java.util.Date;

public class EqupType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUP_TYPE.EQUP_ID
     *
     * @mbggenerated
     */
    private BigDecimal equpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUP_TYPE.EQUP_CODE
     *
     * @mbggenerated
     */
    private String equpCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUP_TYPE.EQUP_NAME
     *
     * @mbggenerated
     */
    private String equpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUP_TYPE.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUP_TYPE.OP_TIME
     *
     * @mbggenerated
     */
    private Date opTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUP_TYPE.OPERATOR
     *
     * @mbggenerated
     */
    private BigDecimal operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EQUP_TYPE.TABLE_NAME
     *
     * @mbggenerated
     */
    private String tableName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUP_TYPE.EQUP_ID
     *
     * @return the value of EQUP_TYPE.EQUP_ID
     *
     * @mbggenerated
     */
    public BigDecimal getEqupId() {
        return equpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUP_TYPE.EQUP_ID
     *
     * @param equpId the value for EQUP_TYPE.EQUP_ID
     *
     * @mbggenerated
     */
    public void setEqupId(BigDecimal equpId) {
        this.equpId = equpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUP_TYPE.EQUP_CODE
     *
     * @return the value of EQUP_TYPE.EQUP_CODE
     *
     * @mbggenerated
     */
    public String getEqupCode() {
        return equpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUP_TYPE.EQUP_CODE
     *
     * @param equpCode the value for EQUP_TYPE.EQUP_CODE
     *
     * @mbggenerated
     */
    public void setEqupCode(String equpCode) {
        this.equpCode = equpCode == null ? null : equpCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUP_TYPE.EQUP_NAME
     *
     * @return the value of EQUP_TYPE.EQUP_NAME
     *
     * @mbggenerated
     */
    public String getEqupName() {
        return equpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUP_TYPE.EQUP_NAME
     *
     * @param equpName the value for EQUP_TYPE.EQUP_NAME
     *
     * @mbggenerated
     */
    public void setEqupName(String equpName) {
        this.equpName = equpName == null ? null : equpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUP_TYPE.STATUS
     *
     * @return the value of EQUP_TYPE.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUP_TYPE.STATUS
     *
     * @param status the value for EQUP_TYPE.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUP_TYPE.OP_TIME
     *
     * @return the value of EQUP_TYPE.OP_TIME
     *
     * @mbggenerated
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUP_TYPE.OP_TIME
     *
     * @param opTime the value for EQUP_TYPE.OP_TIME
     *
     * @mbggenerated
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUP_TYPE.OPERATOR
     *
     * @return the value of EQUP_TYPE.OPERATOR
     *
     * @mbggenerated
     */
    public BigDecimal getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUP_TYPE.OPERATOR
     *
     * @param operator the value for EQUP_TYPE.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(BigDecimal operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EQUP_TYPE.TABLE_NAME
     *
     * @return the value of EQUP_TYPE.TABLE_NAME
     *
     * @mbggenerated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EQUP_TYPE.TABLE_NAME
     *
     * @param tableName the value for EQUP_TYPE.TABLE_NAME
     *
     * @mbggenerated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }
}