package com.unique.mb.po;

import java.math.BigDecimal;

public class TestResultDet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_RESULT_DET.TEST_RESULT_DET_ID
     *
     * @mbggenerated
     */
    private BigDecimal testResultDetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_RESULT_DET.TEST_RESULT_ID
     *
     * @mbggenerated
     */
    private BigDecimal testResultId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_RESULT_DET.ALERT_GRADE
     *
     * @mbggenerated
     */
    private BigDecimal alertGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_RESULT_DET.DOCTOR_ALERT_CON
     *
     * @mbggenerated
     */
    private String doctorAlertCon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_RESULT_DET.USER_ALERT_RESULT
     *
     * @mbggenerated
     */
    private String userAlertResult;

    private String userHealthySuggest;
    
    private BigDecimal kpiId;
    
    private String isAlert;
    
	public String getIsAlert() {
		return isAlert;
	}

	public void setIsAlert(String isAlert) {
		this.isAlert = isAlert;
	}

	public BigDecimal getKpiId() {
		return kpiId;
	}

	public void setKpiId(BigDecimal kpiId) {
		this.kpiId = kpiId;
	}

	public String getUserHealthySuggest() {
		return userHealthySuggest;
	}

	public void setUserHealthySuggest(String userHealthySuggest) {
		this.userHealthySuggest = userHealthySuggest;
	}

	private BigDecimal doStatus = new BigDecimal(0);
    private String doWay;
    
    public BigDecimal getDoStatus() {
		return doStatus;
	}

	public void setDoStatus(BigDecimal doStatus) {
		this.doStatus = doStatus;
	}

	public String getDoWay() {
		return doWay;
	}

	public void setDoWay(String doWay) {
		this.doWay = doWay;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_RESULT_DET.TEST_RESULT_DET_ID
     *
     * @return the value of TEST_RESULT_DET.TEST_RESULT_DET_ID
     *
     * @mbggenerated
     */
    public BigDecimal getTestResultDetId() {
        return testResultDetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_RESULT_DET.TEST_RESULT_DET_ID
     *
     * @param testResultDetId the value for TEST_RESULT_DET.TEST_RESULT_DET_ID
     *
     * @mbggenerated
     */
    public void setTestResultDetId(BigDecimal testResultDetId) {
        this.testResultDetId = testResultDetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_RESULT_DET.TEST_RESULT_ID
     *
     * @return the value of TEST_RESULT_DET.TEST_RESULT_ID
     *
     * @mbggenerated
     */
    public BigDecimal getTestResultId() {
        return testResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_RESULT_DET.TEST_RESULT_ID
     *
     * @param testResultId the value for TEST_RESULT_DET.TEST_RESULT_ID
     *
     * @mbggenerated
     */
    public void setTestResultId(BigDecimal testResultId) {
        this.testResultId = testResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_RESULT_DET.ALERT_GRADE
     *
     * @return the value of TEST_RESULT_DET.ALERT_GRADE
     *
     * @mbggenerated
     */
    public BigDecimal getAlertGrade() {
        return alertGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_RESULT_DET.ALERT_GRADE
     *
     * @param alertGrade the value for TEST_RESULT_DET.ALERT_GRADE
     *
     * @mbggenerated
     */
    public void setAlertGrade(BigDecimal alertGrade) {
        this.alertGrade = alertGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_RESULT_DET.DOCTOR_ALERT_CON
     *
     * @return the value of TEST_RESULT_DET.DOCTOR_ALERT_CON
     *
     * @mbggenerated
     */
    public String getDoctorAlertCon() {
        return doctorAlertCon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_RESULT_DET.DOCTOR_ALERT_CON
     *
     * @param doctorAlertCon the value for TEST_RESULT_DET.DOCTOR_ALERT_CON
     *
     * @mbggenerated
     */
    public void setDoctorAlertCon(String doctorAlertCon) {
        this.doctorAlertCon = doctorAlertCon == null ? null : doctorAlertCon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_RESULT_DET.USER_ALERT_RESULT
     *
     * @return the value of TEST_RESULT_DET.USER_ALERT_RESULT
     *
     * @mbggenerated
     */
    public String getUserAlertResult() {
        return userAlertResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_RESULT_DET.USER_ALERT_RESULT
     *
     * @param userAlertResult the value for TEST_RESULT_DET.USER_ALERT_RESULT
     *
     * @mbggenerated
     */
    public void setUserAlertResult(String userAlertResult) {
        this.userAlertResult = userAlertResult == null ? null : userAlertResult.trim();
    }
}