package com.unique.mb.po;

import java.math.BigDecimal;
import java.util.List;

public class TestResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_RESULT.TEST_RESULT_ID
     *
     * @mbggenerated
     */
    private BigDecimal testResultId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_RESULT.TEST_ID
     *
     * @mbggenerated
     */
    private BigDecimal testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_RESULT.TEST_TYPE
     *
     * @mbggenerated
     */
    private String testType;
    
    private List<TestResultDet> testResultDets;

    public List<TestResultDet> getTestResultDets() {
		return testResultDets;
	}

	public void setTestResultDets(List<TestResultDet> testResultDets) {
		this.testResultDets = testResultDets;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_RESULT.TEST_RESULT_ID
     *
     * @return the value of TEST_RESULT.TEST_RESULT_ID
     *
     * @mbggenerated
     */
    public BigDecimal getTestResultId() {
        return testResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_RESULT.TEST_RESULT_ID
     *
     * @param testResultId the value for TEST_RESULT.TEST_RESULT_ID
     *
     * @mbggenerated
     */
    public void setTestResultId(BigDecimal testResultId) {
        this.testResultId = testResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_RESULT.TEST_ID
     *
     * @return the value of TEST_RESULT.TEST_ID
     *
     * @mbggenerated
     */
    public BigDecimal getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_RESULT.TEST_ID
     *
     * @param testId the value for TEST_RESULT.TEST_ID
     *
     * @mbggenerated
     */
    public void setTestId(BigDecimal testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_RESULT.TEST_TYPE
     *
     * @return the value of TEST_RESULT.TEST_TYPE
     *
     * @mbggenerated
     */
    public String getTestType() {
        return testType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_RESULT.TEST_TYPE
     *
     * @param testType the value for TEST_RESULT.TEST_TYPE
     *
     * @mbggenerated
     */
    public void setTestType(String testType) {
        this.testType = testType == null ? null : testType.trim();
    }
}