package com.unique.mb.po;

import java.math.BigDecimal;
import java.util.Date;

public class UserHeartRateTest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_HEART_RATE_TEST.TEST_ID
     *
     * @mbggenerated
     */
    private BigDecimal testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_HEART_RATE_TEST.USER_ID
     *
     * @mbggenerated
     */
    private BigDecimal userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_HEART_RATE_TEST.SOURCE_ID
     *
     * @mbggenerated
     */
    private BigDecimal sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_HEART_RATE_TEST.USER_DEVICE_ID
     *
     * @mbggenerated
     */
    private BigDecimal userDeviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_HEART_RATE_TEST.TEST_TIME
     *
     * @mbggenerated
     */
    private Date testTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_HEART_RATE_TEST.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_HEART_RATE_TEST.TEST_RESULT
     *
     * @mbggenerated
     */
    private String testResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_HEART_RATE_TEST.INPUT_MODE
     *
     * @mbggenerated
     */
    private String inputMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_HEART_RATE_TEST.USER_DEVICE_CODE
     *
     * @mbggenerated
     */
    private String userDeviceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_HEART_RATE_TEST.DEVICE_TOKEN
     *
     * @mbggenerated
     */
    private String deviceToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_HEART_RATE_TEST.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_HEART_RATE_TEST.IS_ALARM
     *
     * @mbggenerated
     */
    private String isAlarm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_HEART_RATE_TEST.TEST_TIME_ID
     *
     * @mbggenerated
     */
    private BigDecimal testTimeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_HEART_RATE_TEST.RATE
     *
     * @mbggenerated
     */
    private BigDecimal rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_HEART_RATE_TEST.TEST_TYPE
     *
     * @mbggenerated
     */
    private String testType;
    
    private BigDecimal testSourceId;

    public BigDecimal getTestSourceId() {
		return testSourceId;
	}

	public void setTestSourceId(BigDecimal testSourceId) {
		this.testSourceId = testSourceId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_HEART_RATE_TEST.TEST_ID
     *
     * @return the value of USER_HEART_RATE_TEST.TEST_ID
     *
     * @mbggenerated
     */
    public BigDecimal getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_HEART_RATE_TEST.TEST_ID
     *
     * @param testId the value for USER_HEART_RATE_TEST.TEST_ID
     *
     * @mbggenerated
     */
    public void setTestId(BigDecimal testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_HEART_RATE_TEST.USER_ID
     *
     * @return the value of USER_HEART_RATE_TEST.USER_ID
     *
     * @mbggenerated
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_HEART_RATE_TEST.USER_ID
     *
     * @param userId the value for USER_HEART_RATE_TEST.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_HEART_RATE_TEST.SOURCE_ID
     *
     * @return the value of USER_HEART_RATE_TEST.SOURCE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_HEART_RATE_TEST.SOURCE_ID
     *
     * @param sourceId the value for USER_HEART_RATE_TEST.SOURCE_ID
     *
     * @mbggenerated
     */
    public void setSourceId(BigDecimal sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_HEART_RATE_TEST.USER_DEVICE_ID
     *
     * @return the value of USER_HEART_RATE_TEST.USER_DEVICE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getUserDeviceId() {
        return userDeviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_HEART_RATE_TEST.USER_DEVICE_ID
     *
     * @param userDeviceId the value for USER_HEART_RATE_TEST.USER_DEVICE_ID
     *
     * @mbggenerated
     */
    public void setUserDeviceId(BigDecimal userDeviceId) {
        this.userDeviceId = userDeviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_HEART_RATE_TEST.TEST_TIME
     *
     * @return the value of USER_HEART_RATE_TEST.TEST_TIME
     *
     * @mbggenerated
     */
    public Date getTestTime() {
        return testTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_HEART_RATE_TEST.TEST_TIME
     *
     * @param testTime the value for USER_HEART_RATE_TEST.TEST_TIME
     *
     * @mbggenerated
     */
    public void setTestTime(Date testTime) {
        this.testTime = testTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_HEART_RATE_TEST.USER_NAME
     *
     * @return the value of USER_HEART_RATE_TEST.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_HEART_RATE_TEST.USER_NAME
     *
     * @param userName the value for USER_HEART_RATE_TEST.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_HEART_RATE_TEST.TEST_RESULT
     *
     * @return the value of USER_HEART_RATE_TEST.TEST_RESULT
     *
     * @mbggenerated
     */
    public String getTestResult() {
        return testResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_HEART_RATE_TEST.TEST_RESULT
     *
     * @param testResult the value for USER_HEART_RATE_TEST.TEST_RESULT
     *
     * @mbggenerated
     */
    public void setTestResult(String testResult) {
        this.testResult = testResult == null ? null : testResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_HEART_RATE_TEST.INPUT_MODE
     *
     * @return the value of USER_HEART_RATE_TEST.INPUT_MODE
     *
     * @mbggenerated
     */
    public String getInputMode() {
        return inputMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_HEART_RATE_TEST.INPUT_MODE
     *
     * @param inputMode the value for USER_HEART_RATE_TEST.INPUT_MODE
     *
     * @mbggenerated
     */
    public void setInputMode(String inputMode) {
        this.inputMode = inputMode == null ? null : inputMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_HEART_RATE_TEST.USER_DEVICE_CODE
     *
     * @return the value of USER_HEART_RATE_TEST.USER_DEVICE_CODE
     *
     * @mbggenerated
     */
    public String getUserDeviceCode() {
        return userDeviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_HEART_RATE_TEST.USER_DEVICE_CODE
     *
     * @param userDeviceCode the value for USER_HEART_RATE_TEST.USER_DEVICE_CODE
     *
     * @mbggenerated
     */
    public void setUserDeviceCode(String userDeviceCode) {
        this.userDeviceCode = userDeviceCode == null ? null : userDeviceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_HEART_RATE_TEST.DEVICE_TOKEN
     *
     * @return the value of USER_HEART_RATE_TEST.DEVICE_TOKEN
     *
     * @mbggenerated
     */
    public String getDeviceToken() {
        return deviceToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_HEART_RATE_TEST.DEVICE_TOKEN
     *
     * @param deviceToken the value for USER_HEART_RATE_TEST.DEVICE_TOKEN
     *
     * @mbggenerated
     */
    public void setDeviceToken(String deviceToken) {
        this.deviceToken = deviceToken == null ? null : deviceToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_HEART_RATE_TEST.STATUS
     *
     * @return the value of USER_HEART_RATE_TEST.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_HEART_RATE_TEST.STATUS
     *
     * @param status the value for USER_HEART_RATE_TEST.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_HEART_RATE_TEST.IS_ALARM
     *
     * @return the value of USER_HEART_RATE_TEST.IS_ALARM
     *
     * @mbggenerated
     */
    public String getIsAlarm() {
        return isAlarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_HEART_RATE_TEST.IS_ALARM
     *
     * @param isAlarm the value for USER_HEART_RATE_TEST.IS_ALARM
     *
     * @mbggenerated
     */
    public void setIsAlarm(String isAlarm) {
        this.isAlarm = isAlarm == null ? null : isAlarm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_HEART_RATE_TEST.TEST_TIME_ID
     *
     * @return the value of USER_HEART_RATE_TEST.TEST_TIME_ID
     *
     * @mbggenerated
     */
    public BigDecimal getTestTimeId() {
        return testTimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_HEART_RATE_TEST.TEST_TIME_ID
     *
     * @param testTimeId the value for USER_HEART_RATE_TEST.TEST_TIME_ID
     *
     * @mbggenerated
     */
    public void setTestTimeId(BigDecimal testTimeId) {
        this.testTimeId = testTimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_HEART_RATE_TEST.RATE
     *
     * @return the value of USER_HEART_RATE_TEST.RATE
     *
     * @mbggenerated
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_HEART_RATE_TEST.RATE
     *
     * @param rate the value for USER_HEART_RATE_TEST.RATE
     *
     * @mbggenerated
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_HEART_RATE_TEST.TEST_TYPE
     *
     * @return the value of USER_HEART_RATE_TEST.TEST_TYPE
     *
     * @mbggenerated
     */
    public String getTestType() {
        return testType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_HEART_RATE_TEST.TEST_TYPE
     *
     * @param testType the value for USER_HEART_RATE_TEST.TEST_TYPE
     *
     * @mbggenerated
     */
    public void setTestType(String testType) {
        this.testType = testType == null ? null : testType.trim();
    }
}