package com.unique.mb.po;

import java.math.BigDecimal;

public class UserElectrocardioResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ELECTROCARDIO_RESULT.RESULT_ID
     *
     * @mbggenerated
     */
    private BigDecimal resultId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ELECTROCARDIO_RESULT.TEST_ID
     *
     * @mbggenerated
     */
    private BigDecimal testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ELECTROCARDIO_RESULT.CONTEXT
     *
     * @mbggenerated
     */
    private String context;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ELECTROCARDIO_RESULT.RESULT_ID
     *
     * @return the value of USER_ELECTROCARDIO_RESULT.RESULT_ID
     *
     * @mbggenerated
     */
    public BigDecimal getResultId() {
        return resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ELECTROCARDIO_RESULT.RESULT_ID
     *
     * @param resultId the value for USER_ELECTROCARDIO_RESULT.RESULT_ID
     *
     * @mbggenerated
     */
    public void setResultId(BigDecimal resultId) {
        this.resultId = resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ELECTROCARDIO_RESULT.TEST_ID
     *
     * @return the value of USER_ELECTROCARDIO_RESULT.TEST_ID
     *
     * @mbggenerated
     */
    public BigDecimal getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ELECTROCARDIO_RESULT.TEST_ID
     *
     * @param testId the value for USER_ELECTROCARDIO_RESULT.TEST_ID
     *
     * @mbggenerated
     */
    public void setTestId(BigDecimal testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ELECTROCARDIO_RESULT.CONTEXT
     *
     * @return the value of USER_ELECTROCARDIO_RESULT.CONTEXT
     *
     * @mbggenerated
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ELECTROCARDIO_RESULT.CONTEXT
     *
     * @param context the value for USER_ELECTROCARDIO_RESULT.CONTEXT
     *
     * @mbggenerated
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }
}