package com.unique.order.po;

import java.math.BigDecimal;
import java.util.Date;

public class McOrderBillDet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_BILL_DET.BILL_ID
     *
     * @mbggenerated
     */
    private BigDecimal billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_BILL_DET.MC__BILL_ID
     *
     * @mbggenerated
     */
    private BigDecimal mcBillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_BILL_DET.SRC_BILL_ID
     *
     * @mbggenerated
     */
    private BigDecimal srcBillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_BILL_DET.BILL_MONEY
     *
     * @mbggenerated
     */
    private BigDecimal billMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_BILL_DET.REAL_MONEY
     *
     * @mbggenerated
     */
    private BigDecimal realMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_BILL_DET.BILL_NUM
     *
     * @mbggenerated
     */
    private BigDecimal billNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_BILL_DET.ALL_MONEY
     *
     * @mbggenerated
     */
    private BigDecimal allMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_BILL_DET.ALL_REAL_MONEY
     *
     * @mbggenerated
     */
    private BigDecimal allRealMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_BILL_DET.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_BILL_DET.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_BILL_DET.BILL_ID
     *
     * @return the value of MC_ORDER_BILL_DET.BILL_ID
     *
     * @mbggenerated
     */
    public BigDecimal getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_BILL_DET.BILL_ID
     *
     * @param billId the value for MC_ORDER_BILL_DET.BILL_ID
     *
     * @mbggenerated
     */
    public void setBillId(BigDecimal billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_BILL_DET.MC__BILL_ID
     *
     * @return the value of MC_ORDER_BILL_DET.MC__BILL_ID
     *
     * @mbggenerated
     */
    public BigDecimal getMcBillId() {
        return mcBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_BILL_DET.MC__BILL_ID
     *
     * @param mcBillId the value for MC_ORDER_BILL_DET.MC__BILL_ID
     *
     * @mbggenerated
     */
    public void setMcBillId(BigDecimal mcBillId) {
        this.mcBillId = mcBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_BILL_DET.SRC_BILL_ID
     *
     * @return the value of MC_ORDER_BILL_DET.SRC_BILL_ID
     *
     * @mbggenerated
     */
    public BigDecimal getSrcBillId() {
        return srcBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_BILL_DET.SRC_BILL_ID
     *
     * @param srcBillId the value for MC_ORDER_BILL_DET.SRC_BILL_ID
     *
     * @mbggenerated
     */
    public void setSrcBillId(BigDecimal srcBillId) {
        this.srcBillId = srcBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_BILL_DET.BILL_MONEY
     *
     * @return the value of MC_ORDER_BILL_DET.BILL_MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getBillMoney() {
        return billMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_BILL_DET.BILL_MONEY
     *
     * @param billMoney the value for MC_ORDER_BILL_DET.BILL_MONEY
     *
     * @mbggenerated
     */
    public void setBillMoney(BigDecimal billMoney) {
        this.billMoney = billMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_BILL_DET.REAL_MONEY
     *
     * @return the value of MC_ORDER_BILL_DET.REAL_MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getRealMoney() {
        return realMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_BILL_DET.REAL_MONEY
     *
     * @param realMoney the value for MC_ORDER_BILL_DET.REAL_MONEY
     *
     * @mbggenerated
     */
    public void setRealMoney(BigDecimal realMoney) {
        this.realMoney = realMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_BILL_DET.BILL_NUM
     *
     * @return the value of MC_ORDER_BILL_DET.BILL_NUM
     *
     * @mbggenerated
     */
    public BigDecimal getBillNum() {
        return billNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_BILL_DET.BILL_NUM
     *
     * @param billNum the value for MC_ORDER_BILL_DET.BILL_NUM
     *
     * @mbggenerated
     */
    public void setBillNum(BigDecimal billNum) {
        this.billNum = billNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_BILL_DET.ALL_MONEY
     *
     * @return the value of MC_ORDER_BILL_DET.ALL_MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getAllMoney() {
        return allMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_BILL_DET.ALL_MONEY
     *
     * @param allMoney the value for MC_ORDER_BILL_DET.ALL_MONEY
     *
     * @mbggenerated
     */
    public void setAllMoney(BigDecimal allMoney) {
        this.allMoney = allMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_BILL_DET.ALL_REAL_MONEY
     *
     * @return the value of MC_ORDER_BILL_DET.ALL_REAL_MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getAllRealMoney() {
        return allRealMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_BILL_DET.ALL_REAL_MONEY
     *
     * @param allRealMoney the value for MC_ORDER_BILL_DET.ALL_REAL_MONEY
     *
     * @mbggenerated
     */
    public void setAllRealMoney(BigDecimal allRealMoney) {
        this.allRealMoney = allRealMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_BILL_DET.STATUS
     *
     * @return the value of MC_ORDER_BILL_DET.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_BILL_DET.STATUS
     *
     * @param status the value for MC_ORDER_BILL_DET.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_BILL_DET.CREATE_TIME
     *
     * @return the value of MC_ORDER_BILL_DET.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_BILL_DET.CREATE_TIME
     *
     * @param createTime the value for MC_ORDER_BILL_DET.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}