package com.unique.order.po;

import java.math.BigDecimal;
import java.util.Date;

public class McOrderDivide {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_DIVIDE.DIVIDE_ID
     *
     * @mbggenerated
     */
    private BigDecimal divideId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_DIVIDE.CHANNEL_ID
     *
     * @mbggenerated
     */
    private BigDecimal channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_DIVIDE.MC_PRODUCT_ID
     *
     * @mbggenerated
     */
    private BigDecimal mcProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_DIVIDE.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_DIVIDE.CHANNEL_NAME
     *
     * @mbggenerated
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_DIVIDE.PRODUCT_NAME
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_DIVIDE.DIVIDE_WAY
     *
     * @mbggenerated
     */
    private String divideWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_DIVIDE.DIVIDE_VALUE
     *
     * @mbggenerated
     */
    private BigDecimal divideValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_DIVIDE.DIVIDE_MONEY
     *
     * @mbggenerated
     */
    private BigDecimal divideMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_DIVIDE.ORDER_PRODUCT_ID
     *
     * @mbggenerated
     */
    private BigDecimal orderProductId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_DIVIDE.DIVIDE_ID
     *
     * @return the value of MC_ORDER_DIVIDE.DIVIDE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getDivideId() {
        return divideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_DIVIDE.DIVIDE_ID
     *
     * @param divideId the value for MC_ORDER_DIVIDE.DIVIDE_ID
     *
     * @mbggenerated
     */
    public void setDivideId(BigDecimal divideId) {
        this.divideId = divideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_DIVIDE.CHANNEL_ID
     *
     * @return the value of MC_ORDER_DIVIDE.CHANNEL_ID
     *
     * @mbggenerated
     */
    public BigDecimal getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_DIVIDE.CHANNEL_ID
     *
     * @param channelId the value for MC_ORDER_DIVIDE.CHANNEL_ID
     *
     * @mbggenerated
     */
    public void setChannelId(BigDecimal channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_DIVIDE.MC_PRODUCT_ID
     *
     * @return the value of MC_ORDER_DIVIDE.MC_PRODUCT_ID
     *
     * @mbggenerated
     */
    public BigDecimal getMcProductId() {
        return mcProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_DIVIDE.MC_PRODUCT_ID
     *
     * @param mcProductId the value for MC_ORDER_DIVIDE.MC_PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setMcProductId(BigDecimal mcProductId) {
        this.mcProductId = mcProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_DIVIDE.CREATE_TIME
     *
     * @return the value of MC_ORDER_DIVIDE.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_DIVIDE.CREATE_TIME
     *
     * @param createTime the value for MC_ORDER_DIVIDE.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_DIVIDE.CHANNEL_NAME
     *
     * @return the value of MC_ORDER_DIVIDE.CHANNEL_NAME
     *
     * @mbggenerated
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_DIVIDE.CHANNEL_NAME
     *
     * @param channelName the value for MC_ORDER_DIVIDE.CHANNEL_NAME
     *
     * @mbggenerated
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_DIVIDE.PRODUCT_NAME
     *
     * @return the value of MC_ORDER_DIVIDE.PRODUCT_NAME
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_DIVIDE.PRODUCT_NAME
     *
     * @param productName the value for MC_ORDER_DIVIDE.PRODUCT_NAME
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_DIVIDE.DIVIDE_WAY
     *
     * @return the value of MC_ORDER_DIVIDE.DIVIDE_WAY
     *
     * @mbggenerated
     */
    public String getDivideWay() {
        return divideWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_DIVIDE.DIVIDE_WAY
     *
     * @param divideWay the value for MC_ORDER_DIVIDE.DIVIDE_WAY
     *
     * @mbggenerated
     */
    public void setDivideWay(String divideWay) {
        this.divideWay = divideWay == null ? null : divideWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_DIVIDE.DIVIDE_VALUE
     *
     * @return the value of MC_ORDER_DIVIDE.DIVIDE_VALUE
     *
     * @mbggenerated
     */
    public BigDecimal getDivideValue() {
        return divideValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_DIVIDE.DIVIDE_VALUE
     *
     * @param divideValue the value for MC_ORDER_DIVIDE.DIVIDE_VALUE
     *
     * @mbggenerated
     */
    public void setDivideValue(BigDecimal divideValue) {
        this.divideValue = divideValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_DIVIDE.DIVIDE_MONEY
     *
     * @return the value of MC_ORDER_DIVIDE.DIVIDE_MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getDivideMoney() {
        return divideMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_DIVIDE.DIVIDE_MONEY
     *
     * @param divideMoney the value for MC_ORDER_DIVIDE.DIVIDE_MONEY
     *
     * @mbggenerated
     */
    public void setDivideMoney(BigDecimal divideMoney) {
        this.divideMoney = divideMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_DIVIDE.ORDER_PRODUCT_ID
     *
     * @return the value of MC_ORDER_DIVIDE.ORDER_PRODUCT_ID
     *
     * @mbggenerated
     */
    public BigDecimal getOrderProductId() {
        return orderProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_DIVIDE.ORDER_PRODUCT_ID
     *
     * @param orderProductId the value for MC_ORDER_DIVIDE.ORDER_PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setOrderProductId(BigDecimal orderProductId) {
        this.orderProductId = orderProductId;
    }
}