package com.unique.order.po;

import java.math.BigDecimal;

public class McOrderBackDet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_BACK_DET.ORDER_BACK_ID
     *
     * @mbggenerated
     */
    private BigDecimal backOrderDetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_BACK_DET.ORDER_ID
     *
     * @mbggenerated
     */
    private BigDecimal orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_BACK_DET.MC_PRODUCT_ID
     *
     * @mbggenerated
     */
    private BigDecimal mcProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_BACK_DET.ORDER_PRODUCT_ID
     *
     * @mbggenerated
     */
    private BigDecimal orderProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_BACK_DET.BACK_ORDER_ID
     *
     * @mbggenerated
     */
    private BigDecimal backOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_BACK_DET.PRODUCT_TYPE_ID
     *
     * @mbggenerated
     */
    private BigDecimal productTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_BACK_DET.PRODUCT_NAME
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_BACK_DET.PRODUCT_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_BACK_DET.BACK_NUM
     *
     * @mbggenerated
     */
    private BigDecimal backNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_ORDER_BACK_DET.BACK_MONEY
     *
     * @mbggenerated
     */
    private BigDecimal backMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_BACK_DET.ORDER_BACK_ID
     *
     * @return the value of MC_ORDER_BACK_DET.ORDER_BACK_ID
     *
     * @mbggenerated
     */
    public BigDecimal getBackOrderDetId() {
        return backOrderDetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_BACK_DET.ORDER_BACK_ID
     *
     * @param orderBackId the value for MC_ORDER_BACK_DET.ORDER_BACK_ID
     *
     * @mbggenerated
     */
    public void setBackOrderDetId(BigDecimal backOrderDetId) {
        this.backOrderDetId = backOrderDetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_BACK_DET.ORDER_ID
     *
     * @return the value of MC_ORDER_BACK_DET.ORDER_ID
     *
     * @mbggenerated
     */
    public BigDecimal getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_BACK_DET.ORDER_ID
     *
     * @param orderId the value for MC_ORDER_BACK_DET.ORDER_ID
     *
     * @mbggenerated
     */
    public void setOrderId(BigDecimal orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_BACK_DET.MC_PRODUCT_ID
     *
     * @return the value of MC_ORDER_BACK_DET.MC_PRODUCT_ID
     *
     * @mbggenerated
     */
    public BigDecimal getMcProductId() {
        return mcProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_BACK_DET.MC_PRODUCT_ID
     *
     * @param mcProductId the value for MC_ORDER_BACK_DET.MC_PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setMcProductId(BigDecimal mcProductId) {
        this.mcProductId = mcProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_BACK_DET.ORDER_PRODUCT_ID
     *
     * @return the value of MC_ORDER_BACK_DET.ORDER_PRODUCT_ID
     *
     * @mbggenerated
     */
    public BigDecimal getOrderProductId() {
        return orderProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_BACK_DET.ORDER_PRODUCT_ID
     *
     * @param orderProductId the value for MC_ORDER_BACK_DET.ORDER_PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setOrderProductId(BigDecimal orderProductId) {
        this.orderProductId = orderProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_BACK_DET.BACK_ORDER_ID
     *
     * @return the value of MC_ORDER_BACK_DET.BACK_ORDER_ID
     *
     * @mbggenerated
     */
    public BigDecimal getBackOrderId() {
        return backOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_BACK_DET.BACK_ORDER_ID
     *
     * @param backOrderId the value for MC_ORDER_BACK_DET.BACK_ORDER_ID
     *
     * @mbggenerated
     */
    public void setBackOrderId(BigDecimal backOrderId) {
        this.backOrderId = backOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_BACK_DET.PRODUCT_TYPE_ID
     *
     * @return the value of MC_ORDER_BACK_DET.PRODUCT_TYPE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getProductTypeId() {
        return productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_BACK_DET.PRODUCT_TYPE_ID
     *
     * @param productTypeId the value for MC_ORDER_BACK_DET.PRODUCT_TYPE_ID
     *
     * @mbggenerated
     */
    public void setProductTypeId(BigDecimal productTypeId) {
        this.productTypeId = productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_BACK_DET.PRODUCT_NAME
     *
     * @return the value of MC_ORDER_BACK_DET.PRODUCT_NAME
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_BACK_DET.PRODUCT_NAME
     *
     * @param productName the value for MC_ORDER_BACK_DET.PRODUCT_NAME
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_BACK_DET.PRODUCT_PRICE
     *
     * @return the value of MC_ORDER_BACK_DET.PRODUCT_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_BACK_DET.PRODUCT_PRICE
     *
     * @param productPrice the value for MC_ORDER_BACK_DET.PRODUCT_PRICE
     *
     * @mbggenerated
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_BACK_DET.BACK_NUM
     *
     * @return the value of MC_ORDER_BACK_DET.BACK_NUM
     *
     * @mbggenerated
     */
    public BigDecimal getBackNum() {
        return backNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_BACK_DET.BACK_NUM
     *
     * @param backNum the value for MC_ORDER_BACK_DET.BACK_NUM
     *
     * @mbggenerated
     */
    public void setBackNum(BigDecimal backNum) {
        this.backNum = backNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_ORDER_BACK_DET.BACK_MONEY
     *
     * @return the value of MC_ORDER_BACK_DET.BACK_MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getBackMoney() {
        return backMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_ORDER_BACK_DET.BACK_MONEY
     *
     * @param backMoney the value for MC_ORDER_BACK_DET.BACK_MONEY
     *
     * @mbggenerated
     */
    public void setBackMoney(BigDecimal backMoney) {
        this.backMoney = backMoney;
    }
}