package com.unique.user.po;

import java.math.BigDecimal;
import java.util.Date;

/**
 * 用户实体类
 * @author Angel
 *
 */
public class AmsUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.USER_ID
     *
     * @mbggenerated
     */
    private BigDecimal userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.USE_USER_TYPE_ID
     *
     * @mbggenerated
     */

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.DEP_ID
     *
     * @mbggenerated
     */
    private BigDecimal depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.ORG_ID
     *
     * @mbggenerated
     */
    private BigDecimal orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.USER_TYPE_ID
     *
     * @mbggenerated
     */
    private BigDecimal userTypeId;
    private String typeCode;
    public String getTypeCode() {
		return typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.USER_CODE
     *
     * @mbggenerated
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.NICK_NAME
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.BIRTH
     *
     * @mbggenerated
     */
    private String birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.SEX
     *
     * @mbggenerated
     */
    private BigDecimal sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.ID_CARD
     *
     * @mbggenerated
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.FOLK
     *
     * @mbggenerated
     */
    private String folk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.WEDLOCK
     *
     * @mbggenerated
     */
    private String wedlock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.VOCATION
     *
     * @mbggenerated
     */
    private BigDecimal vocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.MONEY_BAG
     *
     * @mbggenerated
     */
    private String moneyBag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.ADDR_TYPE_CODE
     *
     * @mbggenerated
     */
    private String addrTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.ADDR_PRO
     *
     * @mbggenerated
     */
    private String addrPro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.ADDR_CITY
     *
     * @mbggenerated
     */
    private String addrCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.ADDR_COUNTY
     *
     * @mbggenerated
     */
    private String addrCounty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.ADDR_XIANG
     *
     * @mbggenerated
     */
    private String addrXiang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.ADDR_VILL
     *
     * @mbggenerated
     */
    private String addrVill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.ADDR_NUMBER
     *
     * @mbggenerated
     */
    private String addrNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.HOME_ADDR
     *
     * @mbggenerated
     */
    private String homeAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.HOME_ADDR_NUM
     *
     * @mbggenerated
     */
    private String homeAddrNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.HOME_TEL
     *
     * @mbggenerated
     */
    private String homeTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.YB_TYPE
     *
     * @mbggenerated
     */
    private String ybType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.YB_TYPE_CODE
     *
     * @mbggenerated
     */
    private String ybTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.E_MAIL
     *
     * @mbggenerated
     */
    private String eMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.UNIT_ADDR
     *
     * @mbggenerated
     */
    private String unitAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.LOGON_ACCT
     *
     * @mbggenerated
     */
    private String logonAcct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.LOGON_PWD
     *
     * @mbggenerated
     */
    private String logonPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.OPERATOR
     *
     * @mbggenerated
     */
    private BigDecimal operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.OP_TIME
     *
     * @mbggenerated
     */
    private Date opTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.IS_ACTIVE
     *
     * @mbggenerated
     */
    private BigDecimal isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.LOGIN_COUNT
     *
     * @mbggenerated
     */
    private BigDecimal loginCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.Q1
     *
     * @mbggenerated
     */
    private String q1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.A1
     *
     * @mbggenerated
     */
    private String a1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.Q2
     *
     * @mbggenerated
     */
    private String q2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.A2
     *
     * @mbggenerated
     */
    private String a2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.LAST_LOGIN_TIME
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.DEVICE_TOKEN
     *
     * @mbggenerated
     */
    private String deviceToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.IS_ONLINE
     *
     * @mbggenerated
     */
    private String isOnline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMS_USER.REG_WAY
     *
     * @mbggenerated
     */
    private String pushCode;
    
    private String allergicDrug;	//过敏药品
    private String anaphylactogen;	//其他过敏源
    private String isSmoking;		//是否抽烟y是n否
    private String isDrinking;		//是否饮酒y是n否
    private String isHealthRecordData; //是否获取健康档案数据y是n否
    private String healtyRecordId;  //健康档案号
    
    private int age;  	//年龄
    
    public BigDecimal getUserWeight() {
		return userWeight;
	}

	public void setUserWeight(BigDecimal userWeight) {
		this.userWeight = userWeight;
	}

	public BigDecimal getUserHeight() {
		return userHeight;
	}

	public void setUserHeight(BigDecimal userHeight) {
		this.userHeight = userHeight;
	}

	private BigDecimal userWeight;
    private BigDecimal userHeight;
    
    
    public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public String getHealtyRecordId() {
		return healtyRecordId;
	}

	public void setHealtyRecordId(String healtyRecordId) {
		this.healtyRecordId = healtyRecordId;
	}

	public String getIsHealthRecordData() {
		return isHealthRecordData;
	}

	public void setIsHealthRecordData(String isHealthRecordData) {
		this.isHealthRecordData = isHealthRecordData;
	}

	public String getAllergicDrug() {
		return allergicDrug;
	}

	public void setAllergicDrug(String allergicDrug) {
		this.allergicDrug = allergicDrug;
	}

	public String getAnaphylactogen() {
		return anaphylactogen;
	}

	public void setAnaphylactogen(String anaphylactogen) {
		this.anaphylactogen = anaphylactogen;
	}

	public String getIsSmoking() {
		return isSmoking;
	}

	public void setIsSmoking(String isSmoking) {
		this.isSmoking = isSmoking;
	}

	public String getIsDrinking() {
		return isDrinking;
	}

	public void setIsDrinking(String isDrinking) {
		this.isDrinking = isDrinking;
	}

	public String getPushCode() {
		return pushCode;
	}

	public void setPushCode(String pushCode) {
		this.pushCode = pushCode;
	}

	private BigDecimal regWay;
    private String imgUrl;
    private String mobile;
    public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getImgUrl() {
		return imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.USER_ID
     *
     * @return the value of AMS_USER.USER_ID
     *
     * @mbggenerated
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.USER_ID
     *
     * @param userId the value for AMS_USER.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.DEP_ID
     *
     * @return the value of AMS_USER.DEP_ID
     *
     * @mbggenerated
     */
    public BigDecimal getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.DEP_ID
     *
     * @param depId the value for AMS_USER.DEP_ID
     *
     * @mbggenerated
     */
    public void setDepId(BigDecimal depId) {
        this.depId = depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.ORG_ID
     *
     * @return the value of AMS_USER.ORG_ID
     *
     * @mbggenerated
     */
    public BigDecimal getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.ORG_ID
     *
     * @param orgId the value for AMS_USER.ORG_ID
     *
     * @mbggenerated
     */
    public void setOrgId(BigDecimal orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.USER_TYPE_ID
     *
     * @return the value of AMS_USER.USER_TYPE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getUserTypeId() {
        return userTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.USER_TYPE_ID
     *
     * @param userTypeId the value for AMS_USER.USER_TYPE_ID
     *
     * @mbggenerated
     */
    public void setUserTypeId(BigDecimal userTypeId) {
        this.userTypeId = userTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.USER_CODE
     *
     * @return the value of AMS_USER.USER_CODE
     *
     * @mbggenerated
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.USER_CODE
     *
     * @param userCode the value for AMS_USER.USER_CODE
     *
     * @mbggenerated
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.USER_NAME
     *
     * @return the value of AMS_USER.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.USER_NAME
     *
     * @param userName the value for AMS_USER.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.NICK_NAME
     *
     * @return the value of AMS_USER.NICK_NAME
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.NICK_NAME
     *
     * @param nickName the value for AMS_USER.NICK_NAME
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.BIRTH
     *
     * @return the value of AMS_USER.BIRTH
     *
     * @mbggenerated
     */
    public String getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.BIRTH
     *
     * @param birth the value for AMS_USER.BIRTH
     *
     * @mbggenerated
     */
    public void setBirth(String birth) {
        this.birth = birth == null ? null : birth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.SEX
     *
     * @return the value of AMS_USER.SEX
     *
     * @mbggenerated
     */
    public BigDecimal getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.SEX
     *
     * @param sex the value for AMS_USER.SEX
     *
     * @mbggenerated
     */
    public void setSex(BigDecimal sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.ID_CARD
     *
     * @return the value of AMS_USER.ID_CARD
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.ID_CARD
     *
     * @param idCard the value for AMS_USER.ID_CARD
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.FOLK
     *
     * @return the value of AMS_USER.FOLK
     *
     * @mbggenerated
     */
    public String getFolk() {
        return folk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.FOLK
     *
     * @param folk the value for AMS_USER.FOLK
     *
     * @mbggenerated
     */
    public void setFolk(String folk) {
        this.folk = folk == null ? null : folk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.WEDLOCK
     *
     * @return the value of AMS_USER.WEDLOCK
     *
     * @mbggenerated
     */
    public String getWedlock() {
        return wedlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.WEDLOCK
     *
     * @param wedlock the value for AMS_USER.WEDLOCK
     *
     * @mbggenerated
     */
    public void setWedlock(String wedlock) {
        this.wedlock = wedlock == null ? null : wedlock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.VOCATION
     *
     * @return the value of AMS_USER.VOCATION
     *
     * @mbggenerated
     */
    public BigDecimal getVocation() {
        return vocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.VOCATION
     *
     * @param vocation the value for AMS_USER.VOCATION
     *
     * @mbggenerated
     */
    public void setVocation(BigDecimal vocation) {
        this.vocation = vocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.MONEY_BAG
     *
     * @return the value of AMS_USER.MONEY_BAG
     *
     * @mbggenerated
     */
    public String getMoneyBag() {
        return moneyBag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.MONEY_BAG
     *
     * @param moneyBag the value for AMS_USER.MONEY_BAG
     *
     * @mbggenerated
     */
    public void setMoneyBag(String moneyBag) {
        this.moneyBag = moneyBag == null ? null : moneyBag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.ADDR_TYPE_CODE
     *
     * @return the value of AMS_USER.ADDR_TYPE_CODE
     *
     * @mbggenerated
     */
    public String getAddrTypeCode() {
        return addrTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.ADDR_TYPE_CODE
     *
     * @param addrTypeCode the value for AMS_USER.ADDR_TYPE_CODE
     *
     * @mbggenerated
     */
    public void setAddrTypeCode(String addrTypeCode) {
        this.addrTypeCode = addrTypeCode == null ? null : addrTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.ADDR_PRO
     *
     * @return the value of AMS_USER.ADDR_PRO
     *
     * @mbggenerated
     */
    public String getAddrPro() {
        return addrPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.ADDR_PRO
     *
     * @param addrPro the value for AMS_USER.ADDR_PRO
     *
     * @mbggenerated
     */
    public void setAddrPro(String addrPro) {
        this.addrPro = addrPro == null ? null : addrPro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.ADDR_CITY
     *
     * @return the value of AMS_USER.ADDR_CITY
     *
     * @mbggenerated
     */
    public String getAddrCity() {
        return addrCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.ADDR_CITY
     *
     * @param addrCity the value for AMS_USER.ADDR_CITY
     *
     * @mbggenerated
     */
    public void setAddrCity(String addrCity) {
        this.addrCity = addrCity == null ? null : addrCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.ADDR_COUNTY
     *
     * @return the value of AMS_USER.ADDR_COUNTY
     *
     * @mbggenerated
     */
    public String getAddrCounty() {
        return addrCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.ADDR_COUNTY
     *
     * @param addrCounty the value for AMS_USER.ADDR_COUNTY
     *
     * @mbggenerated
     */
    public void setAddrCounty(String addrCounty) {
        this.addrCounty = addrCounty == null ? null : addrCounty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.ADDR_XIANG
     *
     * @return the value of AMS_USER.ADDR_XIANG
     *
     * @mbggenerated
     */
    public String getAddrXiang() {
        return addrXiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.ADDR_XIANG
     *
     * @param addrXiang the value for AMS_USER.ADDR_XIANG
     *
     * @mbggenerated
     */
    public void setAddrXiang(String addrXiang) {
        this.addrXiang = addrXiang == null ? null : addrXiang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.ADDR_VILL
     *
     * @return the value of AMS_USER.ADDR_VILL
     *
     * @mbggenerated
     */
    public String getAddrVill() {
        return addrVill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.ADDR_VILL
     *
     * @param addrVill the value for AMS_USER.ADDR_VILL
     *
     * @mbggenerated
     */
    public void setAddrVill(String addrVill) {
        this.addrVill = addrVill == null ? null : addrVill.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.ADDR_NUMBER
     *
     * @return the value of AMS_USER.ADDR_NUMBER
     *
     * @mbggenerated
     */
    public String getAddrNumber() {
        return addrNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.ADDR_NUMBER
     *
     * @param addrNumber the value for AMS_USER.ADDR_NUMBER
     *
     * @mbggenerated
     */
    public void setAddrNumber(String addrNumber) {
        this.addrNumber = addrNumber == null ? null : addrNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.HOME_ADDR
     *
     * @return the value of AMS_USER.HOME_ADDR
     *
     * @mbggenerated
     */
    public String getHomeAddr() {
        return homeAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.HOME_ADDR
     *
     * @param homeAddr the value for AMS_USER.HOME_ADDR
     *
     * @mbggenerated
     */
    public void setHomeAddr(String homeAddr) {
        this.homeAddr = homeAddr == null ? null : homeAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.HOME_ADDR_NUM
     *
     * @return the value of AMS_USER.HOME_ADDR_NUM
     *
     * @mbggenerated
     */
    public String getHomeAddrNum() {
        return homeAddrNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.HOME_ADDR_NUM
     *
     * @param homeAddrNum the value for AMS_USER.HOME_ADDR_NUM
     *
     * @mbggenerated
     */
    public void setHomeAddrNum(String homeAddrNum) {
        this.homeAddrNum = homeAddrNum == null ? null : homeAddrNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.HOME_TEL
     *
     * @return the value of AMS_USER.HOME_TEL
     *
     * @mbggenerated
     */
    public String getHomeTel() {
        return homeTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.HOME_TEL
     *
     * @param homeTel the value for AMS_USER.HOME_TEL
     *
     * @mbggenerated
     */
    public void setHomeTel(String homeTel) {
        this.homeTel = homeTel == null ? null : homeTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.YB_TYPE
     *
     * @return the value of AMS_USER.YB_TYPE
     *
     * @mbggenerated
     */
    public String getYbType() {
        return ybType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.YB_TYPE
     *
     * @param ybType the value for AMS_USER.YB_TYPE
     *
     * @mbggenerated
     */
    public void setYbType(String ybType) {
        this.ybType = ybType == null ? null : ybType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.YB_TYPE_CODE
     *
     * @return the value of AMS_USER.YB_TYPE_CODE
     *
     * @mbggenerated
     */
    public String getYbTypeCode() {
        return ybTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.YB_TYPE_CODE
     *
     * @param ybTypeCode the value for AMS_USER.YB_TYPE_CODE
     *
     * @mbggenerated
     */
    public void setYbTypeCode(String ybTypeCode) {
        this.ybTypeCode = ybTypeCode == null ? null : ybTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.E_MAIL
     *
     * @return the value of AMS_USER.E_MAIL
     *
     * @mbggenerated
     */
    public String geteMail() {
        return eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.E_MAIL
     *
     * @param eMail the value for AMS_USER.E_MAIL
     *
     * @mbggenerated
     */
    public void seteMail(String eMail) {
        this.eMail = eMail == null ? null : eMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.UNIT_ADDR
     *
     * @return the value of AMS_USER.UNIT_ADDR
     *
     * @mbggenerated
     */
    public String getUnitAddr() {
        return unitAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.UNIT_ADDR
     *
     * @param unitAddr the value for AMS_USER.UNIT_ADDR
     *
     * @mbggenerated
     */
    public void setUnitAddr(String unitAddr) {
        this.unitAddr = unitAddr == null ? null : unitAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.LOGON_ACCT
     *
     * @return the value of AMS_USER.LOGON_ACCT
     *
     * @mbggenerated
     */
    public String getLogonAcct() {
        return logonAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.LOGON_ACCT
     *
     * @param logonAcct the value for AMS_USER.LOGON_ACCT
     *
     * @mbggenerated
     */
    public void setLogonAcct(String logonAcct) {
        this.logonAcct = logonAcct == null ? null : logonAcct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.LOGON_PWD
     *
     * @return the value of AMS_USER.LOGON_PWD
     *
     * @mbggenerated
     */
    public String getLogonPwd() {
        return logonPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.LOGON_PWD
     *
     * @param logonPwd the value for AMS_USER.LOGON_PWD
     *
     * @mbggenerated
     */
    public void setLogonPwd(String logonPwd) {
        this.logonPwd = logonPwd == null ? null : logonPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.STATUS
     *
     * @return the value of AMS_USER.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.STATUS
     *
     * @param status the value for AMS_USER.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.OPERATOR
     *
     * @return the value of AMS_USER.OPERATOR
     *
     * @mbggenerated
     */
    public BigDecimal getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.OPERATOR
     *
     * @param operator the value for AMS_USER.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(BigDecimal operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.OP_TIME
     *
     * @return the value of AMS_USER.OP_TIME
     *
     * @mbggenerated
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.OP_TIME
     *
     * @param opTime the value for AMS_USER.OP_TIME
     *
     * @mbggenerated
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.IS_ACTIVE
     *
     * @return the value of AMS_USER.IS_ACTIVE
     *
     * @mbggenerated
     */
    public BigDecimal getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.IS_ACTIVE
     *
     * @param isActive the value for AMS_USER.IS_ACTIVE
     *
     * @mbggenerated
     */
    public void setIsActive(BigDecimal isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.LOGIN_COUNT
     *
     * @return the value of AMS_USER.LOGIN_COUNT
     *
     * @mbggenerated
     */
    public BigDecimal getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.LOGIN_COUNT
     *
     * @param loginCount the value for AMS_USER.LOGIN_COUNT
     *
     * @mbggenerated
     */
    public void setLoginCount(BigDecimal loginCount) {
        this.loginCount = loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.Q1
     *
     * @return the value of AMS_USER.Q1
     *
     * @mbggenerated
     */
    public String getQ1() {
        return q1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.Q1
     *
     * @param q1 the value for AMS_USER.Q1
     *
     * @mbggenerated
     */
    public void setQ1(String q1) {
        this.q1 = q1 == null ? null : q1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.A1
     *
     * @return the value of AMS_USER.A1
     *
     * @mbggenerated
     */
    public String getA1() {
        return a1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.A1
     *
     * @param a1 the value for AMS_USER.A1
     *
     * @mbggenerated
     */
    public void setA1(String a1) {
        this.a1 = a1 == null ? null : a1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.Q2
     *
     * @return the value of AMS_USER.Q2
     *
     * @mbggenerated
     */
    public String getQ2() {
        return q2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.Q2
     *
     * @param q2 the value for AMS_USER.Q2
     *
     * @mbggenerated
     */
    public void setQ2(String q2) {
        this.q2 = q2 == null ? null : q2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.A2
     *
     * @return the value of AMS_USER.A2
     *
     * @mbggenerated
     */
    public String getA2() {
        return a2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.A2
     *
     * @param a2 the value for AMS_USER.A2
     *
     * @mbggenerated
     */
    public void setA2(String a2) {
        this.a2 = a2 == null ? null : a2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.CREATE_TIME
     *
     * @return the value of AMS_USER.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.CREATE_TIME
     *
     * @param createTime the value for AMS_USER.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.LAST_LOGIN_TIME
     *
     * @return the value of AMS_USER.LAST_LOGIN_TIME
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.LAST_LOGIN_TIME
     *
     * @param lastLoginTime the value for AMS_USER.LAST_LOGIN_TIME
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.DEVICE_TOKEN
     *
     * @return the value of AMS_USER.DEVICE_TOKEN
     *
     * @mbggenerated
     */
    public String getDeviceToken() {
        return deviceToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.DEVICE_TOKEN
     *
     * @param deviceToken the value for AMS_USER.DEVICE_TOKEN
     *
     * @mbggenerated
     */
    public void setDeviceToken(String deviceToken) {
        this.deviceToken = deviceToken == null ? null : deviceToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.IS_ONLINE
     *
     * @return the value of AMS_USER.IS_ONLINE
     *
     * @mbggenerated
     */
    public String getIsOnline() {
        return isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.IS_ONLINE
     *
     * @param isOnline the value for AMS_USER.IS_ONLINE
     *
     * @mbggenerated
     */
    public void setIsOnline(String isOnline) {
        this.isOnline = isOnline == null ? null : isOnline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMS_USER.REG_WAY
     *
     * @return the value of AMS_USER.REG_WAY
     *
     * @mbggenerated
     */
    public BigDecimal getRegWay() {
        return regWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMS_USER.REG_WAY
     *
     * @param regWay the value for AMS_USER.REG_WAY
     *
     * @mbggenerated
     */
    public void setRegWay(BigDecimal regWay) {
        this.regWay = regWay;
    }
}