package com.unique.user.po;

import java.math.BigDecimal;
import java.util.Date;

public class CardType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD_TYPE.CARD_TYPE_ID
     *
     * @mbggenerated
     */
    private BigDecimal cardTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD_TYPE.CARD_TYPE_NAME
     *
     * @mbggenerated
     */
    private String cardTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD_TYPE.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD_TYPE.OPERATOR
     *
     * @mbggenerated
     */
    private BigDecimal operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD_TYPE.OP_TIME
     *
     * @mbggenerated
     */
    private Date opTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD_TYPE.OPERATOR_NAME
     *
     * @mbggenerated
     */
    private String operatorName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD_TYPE.CARD_TYPE_ID
     *
     * @return the value of CARD_TYPE.CARD_TYPE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getCardTypeId() {
        return cardTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD_TYPE.CARD_TYPE_ID
     *
     * @param cardTypeId the value for CARD_TYPE.CARD_TYPE_ID
     *
     * @mbggenerated
     */
    public void setCardTypeId(BigDecimal cardTypeId) {
        this.cardTypeId = cardTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD_TYPE.CARD_TYPE_NAME
     *
     * @return the value of CARD_TYPE.CARD_TYPE_NAME
     *
     * @mbggenerated
     */
    public String getCardTypeName() {
        return cardTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD_TYPE.CARD_TYPE_NAME
     *
     * @param cardTypeName the value for CARD_TYPE.CARD_TYPE_NAME
     *
     * @mbggenerated
     */
    public void setCardTypeName(String cardTypeName) {
        this.cardTypeName = cardTypeName == null ? null : cardTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD_TYPE.STATUS
     *
     * @return the value of CARD_TYPE.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD_TYPE.STATUS
     *
     * @param status the value for CARD_TYPE.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD_TYPE.OPERATOR
     *
     * @return the value of CARD_TYPE.OPERATOR
     *
     * @mbggenerated
     */
    public BigDecimal getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD_TYPE.OPERATOR
     *
     * @param operator the value for CARD_TYPE.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(BigDecimal operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD_TYPE.OP_TIME
     *
     * @return the value of CARD_TYPE.OP_TIME
     *
     * @mbggenerated
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD_TYPE.OP_TIME
     *
     * @param opTime the value for CARD_TYPE.OP_TIME
     *
     * @mbggenerated
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD_TYPE.OPERATOR_NAME
     *
     * @return the value of CARD_TYPE.OPERATOR_NAME
     *
     * @mbggenerated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD_TYPE.OPERATOR_NAME
     *
     * @param operatorName the value for CARD_TYPE.OPERATOR_NAME
     *
     * @mbggenerated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }
}