package com.unique.user.po;

import java.math.BigDecimal;
import java.util.Date;

public class McMsg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_MSG.MSG_ID
     *
     * @mbggenerated
     */
    private BigDecimal msgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_MSG.MSG_TYPE_ID
     *
     * @mbggenerated
     */
    private BigDecimal msgTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_MSG.USER_ID
     *
     * @mbggenerated
     */
    private BigDecimal userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_MSG.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_MSG.DEVICE_TOKEN
     *
     * @mbggenerated
     */
    private String deviceToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_MSG.MSG_TITLE
     *
     * @mbggenerated
     */
    private String msgTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_MSG.MSG_CONTENT
     *
     * @mbggenerated
     */
    private String msgContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_MSG.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_MSG.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_MSG.DO_STATUS
     *
     * @mbggenerated
     */
    private BigDecimal doStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_MSG.REVIEW_USER
     *
     * @mbggenerated
     */
    private BigDecimal reviewUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_MSG.REVIEW_TIME
     *
     * @mbggenerated
     */
    private Date reviewTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_MSG.REVIEW_USER_NAME
     *
     * @mbggenerated
     */
    private String reviewUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_MSG.PUBLISH_USER
     *
     * @mbggenerated
     */
    private BigDecimal publishUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_MSG.PUBLISH_TIME
     *
     * @mbggenerated
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_MSG.PUBLISH_USER_NAME
     *
     * @mbggenerated
     */
    private String publishUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_MSG.DO_THING
     *
     * @mbggenerated
     */
    private String doThing;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_MSG.MSG_ID
     *
     * @return the value of MC_MSG.MSG_ID
     *
     * @mbggenerated
     */
    public BigDecimal getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_MSG.MSG_ID
     *
     * @param msgId the value for MC_MSG.MSG_ID
     *
     * @mbggenerated
     */
    public void setMsgId(BigDecimal msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_MSG.MSG_TYPE_ID
     *
     * @return the value of MC_MSG.MSG_TYPE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getMsgTypeId() {
        return msgTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_MSG.MSG_TYPE_ID
     *
     * @param msgTypeId the value for MC_MSG.MSG_TYPE_ID
     *
     * @mbggenerated
     */
    public void setMsgTypeId(BigDecimal msgTypeId) {
        this.msgTypeId = msgTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_MSG.USER_ID
     *
     * @return the value of MC_MSG.USER_ID
     *
     * @mbggenerated
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_MSG.USER_ID
     *
     * @param userId the value for MC_MSG.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_MSG.USER_NAME
     *
     * @return the value of MC_MSG.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_MSG.USER_NAME
     *
     * @param userName the value for MC_MSG.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_MSG.DEVICE_TOKEN
     *
     * @return the value of MC_MSG.DEVICE_TOKEN
     *
     * @mbggenerated
     */
    public String getDeviceToken() {
        return deviceToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_MSG.DEVICE_TOKEN
     *
     * @param deviceToken the value for MC_MSG.DEVICE_TOKEN
     *
     * @mbggenerated
     */
    public void setDeviceToken(String deviceToken) {
        this.deviceToken = deviceToken == null ? null : deviceToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_MSG.MSG_TITLE
     *
     * @return the value of MC_MSG.MSG_TITLE
     *
     * @mbggenerated
     */
    public String getMsgTitle() {
        return msgTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_MSG.MSG_TITLE
     *
     * @param msgTitle the value for MC_MSG.MSG_TITLE
     *
     * @mbggenerated
     */
    public void setMsgTitle(String msgTitle) {
        this.msgTitle = msgTitle == null ? null : msgTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_MSG.MSG_CONTENT
     *
     * @return the value of MC_MSG.MSG_CONTENT
     *
     * @mbggenerated
     */
    public String getMsgContent() {
        return msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_MSG.MSG_CONTENT
     *
     * @param msgContent the value for MC_MSG.MSG_CONTENT
     *
     * @mbggenerated
     */
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent == null ? null : msgContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_MSG.CREATE_TIME
     *
     * @return the value of MC_MSG.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_MSG.CREATE_TIME
     *
     * @param createTime the value for MC_MSG.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_MSG.STATUS
     *
     * @return the value of MC_MSG.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_MSG.STATUS
     *
     * @param status the value for MC_MSG.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_MSG.DO_STATUS
     *
     * @return the value of MC_MSG.DO_STATUS
     *
     * @mbggenerated
     */
    public BigDecimal getDoStatus() {
        return doStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_MSG.DO_STATUS
     *
     * @param doStatus the value for MC_MSG.DO_STATUS
     *
     * @mbggenerated
     */
    public void setDoStatus(BigDecimal doStatus) {
        this.doStatus = doStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_MSG.REVIEW_USER
     *
     * @return the value of MC_MSG.REVIEW_USER
     *
     * @mbggenerated
     */
    public BigDecimal getReviewUser() {
        return reviewUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_MSG.REVIEW_USER
     *
     * @param reviewUser the value for MC_MSG.REVIEW_USER
     *
     * @mbggenerated
     */
    public void setReviewUser(BigDecimal reviewUser) {
        this.reviewUser = reviewUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_MSG.REVIEW_TIME
     *
     * @return the value of MC_MSG.REVIEW_TIME
     *
     * @mbggenerated
     */
    public Date getReviewTime() {
        return reviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_MSG.REVIEW_TIME
     *
     * @param reviewTime the value for MC_MSG.REVIEW_TIME
     *
     * @mbggenerated
     */
    public void setReviewTime(Date reviewTime) {
        this.reviewTime = reviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_MSG.REVIEW_USER_NAME
     *
     * @return the value of MC_MSG.REVIEW_USER_NAME
     *
     * @mbggenerated
     */
    public String getReviewUserName() {
        return reviewUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_MSG.REVIEW_USER_NAME
     *
     * @param reviewUserName the value for MC_MSG.REVIEW_USER_NAME
     *
     * @mbggenerated
     */
    public void setReviewUserName(String reviewUserName) {
        this.reviewUserName = reviewUserName == null ? null : reviewUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_MSG.PUBLISH_USER
     *
     * @return the value of MC_MSG.PUBLISH_USER
     *
     * @mbggenerated
     */
    public BigDecimal getPublishUser() {
        return publishUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_MSG.PUBLISH_USER
     *
     * @param publishUser the value for MC_MSG.PUBLISH_USER
     *
     * @mbggenerated
     */
    public void setPublishUser(BigDecimal publishUser) {
        this.publishUser = publishUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_MSG.PUBLISH_TIME
     *
     * @return the value of MC_MSG.PUBLISH_TIME
     *
     * @mbggenerated
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_MSG.PUBLISH_TIME
     *
     * @param publishTime the value for MC_MSG.PUBLISH_TIME
     *
     * @mbggenerated
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_MSG.PUBLISH_USER_NAME
     *
     * @return the value of MC_MSG.PUBLISH_USER_NAME
     *
     * @mbggenerated
     */
    public String getPublishUserName() {
        return publishUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_MSG.PUBLISH_USER_NAME
     *
     * @param publishUserName the value for MC_MSG.PUBLISH_USER_NAME
     *
     * @mbggenerated
     */
    public void setPublishUserName(String publishUserName) {
        this.publishUserName = publishUserName == null ? null : publishUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_MSG.DO_THING
     *
     * @return the value of MC_MSG.DO_THING
     *
     * @mbggenerated
     */
    public String getDoThing() {
        return doThing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_MSG.DO_THING
     *
     * @param doThing the value for MC_MSG.DO_THING
     *
     * @mbggenerated
     */
    public void setDoThing(String doThing) {
        this.doThing = doThing == null ? null : doThing.trim();
    }
}