package com.unique.user.po;

import java.math.BigDecimal;
import java.util.Date;

public class UserCallLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CALL_LOG.LOG_ID
     *
     * @mbggenerated
     */
    private BigDecimal logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CALL_LOG.USER_ID
     *
     * @mbggenerated
     */
    private BigDecimal userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CALL_LOG.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CALL_LOG.DEVICE_TOKEN
     *
     * @mbggenerated
     */
    private String deviceToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CALL_LOG.CALL_TIME
     *
     * @mbggenerated
     */
    private Date callTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CALL_LOG.SOURCE_ID
     *
     * @mbggenerated
     */
    private BigDecimal sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CALL_LOG.CALL_METHOD
     *
     * @mbggenerated
     */
    private String callMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CALL_LOG.MARKS
     *
     * @mbggenerated
     */
    private BigDecimal marks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CALL_LOG.CALL_MODULE
     *
     * @mbggenerated
     */
    private String callModule;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CALL_LOG.LOG_ID
     *
     * @return the value of USER_CALL_LOG.LOG_ID
     *
     * @mbggenerated
     */
    public BigDecimal getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CALL_LOG.LOG_ID
     *
     * @param logId the value for USER_CALL_LOG.LOG_ID
     *
     * @mbggenerated
     */
    public void setLogId(BigDecimal logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CALL_LOG.USER_ID
     *
     * @return the value of USER_CALL_LOG.USER_ID
     *
     * @mbggenerated
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CALL_LOG.USER_ID
     *
     * @param userId the value for USER_CALL_LOG.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CALL_LOG.USER_NAME
     *
     * @return the value of USER_CALL_LOG.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CALL_LOG.USER_NAME
     *
     * @param userName the value for USER_CALL_LOG.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CALL_LOG.DEVICE_TOKEN
     *
     * @return the value of USER_CALL_LOG.DEVICE_TOKEN
     *
     * @mbggenerated
     */
    public String getDeviceToken() {
        return deviceToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CALL_LOG.DEVICE_TOKEN
     *
     * @param deviceToken the value for USER_CALL_LOG.DEVICE_TOKEN
     *
     * @mbggenerated
     */
    public void setDeviceToken(String deviceToken) {
        this.deviceToken = deviceToken == null ? null : deviceToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CALL_LOG.CALL_TIME
     *
     * @return the value of USER_CALL_LOG.CALL_TIME
     *
     * @mbggenerated
     */
    public Date getCallTime() {
        return callTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CALL_LOG.CALL_TIME
     *
     * @param callTime the value for USER_CALL_LOG.CALL_TIME
     *
     * @mbggenerated
     */
    public void setCallTime(Date callTime) {
        this.callTime = callTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CALL_LOG.SOURCE_ID
     *
     * @return the value of USER_CALL_LOG.SOURCE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CALL_LOG.SOURCE_ID
     *
     * @param sourceId the value for USER_CALL_LOG.SOURCE_ID
     *
     * @mbggenerated
     */
    public void setSourceId(BigDecimal sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CALL_LOG.CALL_METHOD
     *
     * @return the value of USER_CALL_LOG.CALL_METHOD
     *
     * @mbggenerated
     */
    public String getCallMethod() {
        return callMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CALL_LOG.CALL_METHOD
     *
     * @param callMethod the value for USER_CALL_LOG.CALL_METHOD
     *
     * @mbggenerated
     */
    public void setCallMethod(String callMethod) {
        this.callMethod = callMethod == null ? null : callMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CALL_LOG.MARKS
     *
     * @return the value of USER_CALL_LOG.MARKS
     *
     * @mbggenerated
     */
    public BigDecimal getMarks() {
        return marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CALL_LOG.MARKS
     *
     * @param marks the value for USER_CALL_LOG.MARKS
     *
     * @mbggenerated
     */
    public void setMarks(BigDecimal marks) {
        this.marks = marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CALL_LOG.CALL_MODULE
     *
     * @return the value of USER_CALL_LOG.CALL_MODULE
     *
     * @mbggenerated
     */
    public String getCallModule() {
        return callModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CALL_LOG.CALL_MODULE
     *
     * @param callModule the value for USER_CALL_LOG.CALL_MODULE
     *
     * @mbggenerated
     */
    public void setCallModule(String callModule) {
        this.callModule = callModule == null ? null : callModule.trim();
    }
}