package com.unique.user.po;

import java.math.BigDecimal;
import java.util.Date;

public class UserSchedule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_SCHEDULE.SCHEDULE_ID
     *
     * @mbggenerated
     */
    private BigDecimal scheduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_SCHEDULE.USER_ID
     *
     * @mbggenerated
     */
    private BigDecimal userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_SCHEDULE.SCHEDULE_TITLE
     *
     * @mbggenerated
     */
    private String scheduleTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_SCHEDULE.SCHEDULE_CON
     *
     * @mbggenerated
     */
    private String scheduleCon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_SCHEDULE.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_SCHEDULE.BEGIN_TIME
     *
     * @mbggenerated
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_SCHEDULE.END_TIME
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_SCHEDULE.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_SCHEDULE.SCHEDULE_ID
     *
     * @return the value of USER_SCHEDULE.SCHEDULE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getScheduleId() {
        return scheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_SCHEDULE.SCHEDULE_ID
     *
     * @param scheduleId the value for USER_SCHEDULE.SCHEDULE_ID
     *
     * @mbggenerated
     */
    public void setScheduleId(BigDecimal scheduleId) {
        this.scheduleId = scheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_SCHEDULE.USER_ID
     *
     * @return the value of USER_SCHEDULE.USER_ID
     *
     * @mbggenerated
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_SCHEDULE.USER_ID
     *
     * @param userId the value for USER_SCHEDULE.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_SCHEDULE.SCHEDULE_TITLE
     *
     * @return the value of USER_SCHEDULE.SCHEDULE_TITLE
     *
     * @mbggenerated
     */
    public String getScheduleTitle() {
        return scheduleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_SCHEDULE.SCHEDULE_TITLE
     *
     * @param scheduleTitle the value for USER_SCHEDULE.SCHEDULE_TITLE
     *
     * @mbggenerated
     */
    public void setScheduleTitle(String scheduleTitle) {
        this.scheduleTitle = scheduleTitle == null ? null : scheduleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_SCHEDULE.SCHEDULE_CON
     *
     * @return the value of USER_SCHEDULE.SCHEDULE_CON
     *
     * @mbggenerated
     */
    public String getScheduleCon() {
        return scheduleCon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_SCHEDULE.SCHEDULE_CON
     *
     * @param scheduleCon the value for USER_SCHEDULE.SCHEDULE_CON
     *
     * @mbggenerated
     */
    public void setScheduleCon(String scheduleCon) {
        this.scheduleCon = scheduleCon == null ? null : scheduleCon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_SCHEDULE.CREATE_TIME
     *
     * @return the value of USER_SCHEDULE.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_SCHEDULE.CREATE_TIME
     *
     * @param createTime the value for USER_SCHEDULE.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_SCHEDULE.BEGIN_TIME
     *
     * @return the value of USER_SCHEDULE.BEGIN_TIME
     *
     * @mbggenerated
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_SCHEDULE.BEGIN_TIME
     *
     * @param beginTime the value for USER_SCHEDULE.BEGIN_TIME
     *
     * @mbggenerated
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_SCHEDULE.END_TIME
     *
     * @return the value of USER_SCHEDULE.END_TIME
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_SCHEDULE.END_TIME
     *
     * @param endTime the value for USER_SCHEDULE.END_TIME
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_SCHEDULE.STATUS
     *
     * @return the value of USER_SCHEDULE.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_SCHEDULE.STATUS
     *
     * @param status the value for USER_SCHEDULE.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}