package com.unique.user.po;

import java.math.BigDecimal;
import java.util.Date;

public class UserDevice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_DEVICE.USER_DEVICE_ID
     *
     * @mbggenerated
     */
    private BigDecimal userDeviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_DEVICE.DEVICE_TYPE
     *
     * @mbggenerated
     */
    private BigDecimal deviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_DEVICE.USER_ID
     *
     * @mbggenerated
     */
    private BigDecimal userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_DEVICE.USER_DEVICE_TYPE_NAME
     *
     * @mbggenerated
     */
    private String userDeviceTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_DEVICE.USER_DEVICE_CODE
     *
     * @mbggenerated
     */
    private String userDeviceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_DEVICE.USER_DEVICE_NAME
     *
     * @mbggenerated
     */
    private String userDeviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_DEVICE.USER_DEVICE_DESC
     *
     * @mbggenerated
     */
    private String userDeviceDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_DEVICE.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_DEVICE.OP_TIME
     *
     * @mbggenerated
     */
    private Date opTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_DEVICE.OPERATOR
     *
     * @mbggenerated
     */
    private BigDecimal operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_DEVICE.OPERATOR_NAME
     *
     * @mbggenerated
     */
    private String operatorName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_DEVICE.USER_DEVICE_ID
     *
     * @return the value of USER_DEVICE.USER_DEVICE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getUserDeviceId() {
        return userDeviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_DEVICE.USER_DEVICE_ID
     *
     * @param userDeviceId the value for USER_DEVICE.USER_DEVICE_ID
     *
     * @mbggenerated
     */
    public void setUserDeviceId(BigDecimal userDeviceId) {
        this.userDeviceId = userDeviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_DEVICE.DEVICE_TYPE
     *
     * @return the value of USER_DEVICE.DEVICE_TYPE
     *
     * @mbggenerated
     */
    public BigDecimal getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_DEVICE.DEVICE_TYPE
     *
     * @param deviceType the value for USER_DEVICE.DEVICE_TYPE
     *
     * @mbggenerated
     */
    public void setDeviceType(BigDecimal deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_DEVICE.USER_ID
     *
     * @return the value of USER_DEVICE.USER_ID
     *
     * @mbggenerated
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_DEVICE.USER_ID
     *
     * @param userId the value for USER_DEVICE.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_DEVICE.USER_DEVICE_TYPE_NAME
     *
     * @return the value of USER_DEVICE.USER_DEVICE_TYPE_NAME
     *
     * @mbggenerated
     */
    public String getUserDeviceTypeName() {
        return userDeviceTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_DEVICE.USER_DEVICE_TYPE_NAME
     *
     * @param userDeviceTypeName the value for USER_DEVICE.USER_DEVICE_TYPE_NAME
     *
     * @mbggenerated
     */
    public void setUserDeviceTypeName(String userDeviceTypeName) {
        this.userDeviceTypeName = userDeviceTypeName == null ? null : userDeviceTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_DEVICE.USER_DEVICE_CODE
     *
     * @return the value of USER_DEVICE.USER_DEVICE_CODE
     *
     * @mbggenerated
     */
    public String getUserDeviceCode() {
        return userDeviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_DEVICE.USER_DEVICE_CODE
     *
     * @param userDeviceCode the value for USER_DEVICE.USER_DEVICE_CODE
     *
     * @mbggenerated
     */
    public void setUserDeviceCode(String userDeviceCode) {
        this.userDeviceCode = userDeviceCode == null ? null : userDeviceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_DEVICE.USER_DEVICE_NAME
     *
     * @return the value of USER_DEVICE.USER_DEVICE_NAME
     *
     * @mbggenerated
     */
    public String getUserDeviceName() {
        return userDeviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_DEVICE.USER_DEVICE_NAME
     *
     * @param userDeviceName the value for USER_DEVICE.USER_DEVICE_NAME
     *
     * @mbggenerated
     */
    public void setUserDeviceName(String userDeviceName) {
        this.userDeviceName = userDeviceName == null ? null : userDeviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_DEVICE.USER_DEVICE_DESC
     *
     * @return the value of USER_DEVICE.USER_DEVICE_DESC
     *
     * @mbggenerated
     */
    public String getUserDeviceDesc() {
        return userDeviceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_DEVICE.USER_DEVICE_DESC
     *
     * @param userDeviceDesc the value for USER_DEVICE.USER_DEVICE_DESC
     *
     * @mbggenerated
     */
    public void setUserDeviceDesc(String userDeviceDesc) {
        this.userDeviceDesc = userDeviceDesc == null ? null : userDeviceDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_DEVICE.STATUS
     *
     * @return the value of USER_DEVICE.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_DEVICE.STATUS
     *
     * @param status the value for USER_DEVICE.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_DEVICE.OP_TIME
     *
     * @return the value of USER_DEVICE.OP_TIME
     *
     * @mbggenerated
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_DEVICE.OP_TIME
     *
     * @param opTime the value for USER_DEVICE.OP_TIME
     *
     * @mbggenerated
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_DEVICE.OPERATOR
     *
     * @return the value of USER_DEVICE.OPERATOR
     *
     * @mbggenerated
     */
    public BigDecimal getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_DEVICE.OPERATOR
     *
     * @param operator the value for USER_DEVICE.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(BigDecimal operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_DEVICE.OPERATOR_NAME
     *
     * @return the value of USER_DEVICE.OPERATOR_NAME
     *
     * @mbggenerated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_DEVICE.OPERATOR_NAME
     *
     * @param operatorName the value for USER_DEVICE.OPERATOR_NAME
     *
     * @mbggenerated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }
}