package com.unique.org.po;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.unique.core.util.FileUtil;
import com.unique.core.util.StringUtil;
import com.unique.system.po.ImageInfo;

public class Dep {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.DEP_ID
     *
     * @mbggenerated
     */
    private BigDecimal depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.ORG_ID
     *
     * @mbggenerated
     */
    private BigDecimal orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.DEP_TYPE_ID
     *
     * @mbggenerated
     */
    private BigDecimal depTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.DEP_CODE
     *
     * @mbggenerated
     */
    private String depCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.DEP_NAME
     *
     * @mbggenerated
     */
    private String depName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.DEP_ADDR
     *
     * @mbggenerated
     */
    private String depAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.SERIAL_NO
     *
     * @mbggenerated
     */
    private String serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.PARENT_ID
     *
     * @mbggenerated
     */
    private BigDecimal parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.IS_LEAF
     *
     * @mbggenerated
     */
    private String isLeaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.NODE_LEVEL
     *
     * @mbggenerated
     */
    private BigDecimal nodeLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.SORT_RANK
     *
     * @mbggenerated
     */
    private BigDecimal sortRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.OPERATOR
     *
     * @mbggenerated
     */
    private BigDecimal operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.OP_TIME
     *
     * @mbggenerated
     */
    private Date opTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.OPERATOR_NAME
     *
     * @mbggenerated
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.DEP_REMARK
     *
     * @mbggenerated
     */
    private String depRemark;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEP.IS_RECOMMEND
     *
     * @mbggenerated
     */
    private String isRecommend;//是否推荐部门Y是N否
    
    
    
	private String orgName;
    private String hasPeriod;
    private String orgShortName;
    
    private String depIcon;//部门图标
    private String depImage;//部门首页图片
    
    private List<ImageInfo> listImage = new ArrayList<ImageInfo>();
    
    public List<ImageInfo> getListImage() {
		return listImage;
	}
	public void setListImage(List<ImageInfo> listImage) {
		this.listImage = listImage;
	}

	//图片服务器
  	private static final String PIC_SERVER = FileUtil.readProperties("comservice.properties", "picServerOut");
  	
    public String getDepIcon() {
		return depIcon;
	}
	public void setDepIcon(String depIcon) {
		if(!StringUtil.isEmpty(depIcon)){
			this.depIcon = PIC_SERVER+depIcon;
		}
	}
	public String getDepImage() {
		return depImage;
	}
	public void setDepImage(String depImage) {
		if(!StringUtil.isEmpty(depImage)){
			this.depImage = PIC_SERVER+depImage;
		}
	}
	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getHasPeriod() {
		return hasPeriod;
	}

	public void setHasPeriod(String hasPeriod) {
		this.hasPeriod = hasPeriod;
	}

	public String getOrgShortName() {
		return orgShortName;
	}

	public void setOrgShortName(String orgShortName) {
		this.orgShortName = orgShortName;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.DEP_ID
     *
     * @return the value of DEP.DEP_ID
     *
     * @mbggenerated
     */
    public BigDecimal getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.DEP_ID
     *
     * @param depId the value for DEP.DEP_ID
     *
     * @mbggenerated
     */
    public void setDepId(BigDecimal depId) {
        this.depId = depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.ORG_ID
     *
     * @return the value of DEP.ORG_ID
     *
     * @mbggenerated
     */
    public BigDecimal getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.ORG_ID
     *
     * @param orgId the value for DEP.ORG_ID
     *
     * @mbggenerated
     */
    public void setOrgId(BigDecimal orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.DEP_TYPE_ID
     *
     * @return the value of DEP.DEP_TYPE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getDepTypeId() {
        return depTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.DEP_TYPE_ID
     *
     * @param depTypeId the value for DEP.DEP_TYPE_ID
     *
     * @mbggenerated
     */
    public void setDepTypeId(BigDecimal depTypeId) {
        this.depTypeId = depTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.DEP_CODE
     *
     * @return the value of DEP.DEP_CODE
     *
     * @mbggenerated
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.DEP_CODE
     *
     * @param depCode the value for DEP.DEP_CODE
     *
     * @mbggenerated
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode == null ? null : depCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.DEP_NAME
     *
     * @return the value of DEP.DEP_NAME
     *
     * @mbggenerated
     */
    public String getDepName() {
        return depName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.DEP_NAME
     *
     * @param depName the value for DEP.DEP_NAME
     *
     * @mbggenerated
     */
    public void setDepName(String depName) {
        this.depName = depName == null ? null : depName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.DEP_ADDR
     *
     * @return the value of DEP.DEP_ADDR
     *
     * @mbggenerated
     */
    public String getDepAddr() {
        return depAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.DEP_ADDR
     *
     * @param depAddr the value for DEP.DEP_ADDR
     *
     * @mbggenerated
     */
    public void setDepAddr(String depAddr) {
        this.depAddr = depAddr == null ? null : depAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.SERIAL_NO
     *
     * @return the value of DEP.SERIAL_NO
     *
     * @mbggenerated
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.SERIAL_NO
     *
     * @param serialNo the value for DEP.SERIAL_NO
     *
     * @mbggenerated
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo == null ? null : serialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.PARENT_ID
     *
     * @return the value of DEP.PARENT_ID
     *
     * @mbggenerated
     */
    public BigDecimal getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.PARENT_ID
     *
     * @param parentId the value for DEP.PARENT_ID
     *
     * @mbggenerated
     */
    public void setParentId(BigDecimal parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.IS_LEAF
     *
     * @return the value of DEP.IS_LEAF
     *
     * @mbggenerated
     */
    public String getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.IS_LEAF
     *
     * @param isLeaf the value for DEP.IS_LEAF
     *
     * @mbggenerated
     */
    public void setIsLeaf(String isLeaf) {
        this.isLeaf = isLeaf == null ? null : isLeaf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.NODE_LEVEL
     *
     * @return the value of DEP.NODE_LEVEL
     *
     * @mbggenerated
     */
    public BigDecimal getNodeLevel() {
        return nodeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.NODE_LEVEL
     *
     * @param nodeLevel the value for DEP.NODE_LEVEL
     *
     * @mbggenerated
     */
    public void setNodeLevel(BigDecimal nodeLevel) {
        this.nodeLevel = nodeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.SORT_RANK
     *
     * @return the value of DEP.SORT_RANK
     *
     * @mbggenerated
     */
    public BigDecimal getSortRank() {
        return sortRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.SORT_RANK
     *
     * @param sortRank the value for DEP.SORT_RANK
     *
     * @mbggenerated
     */
    public void setSortRank(BigDecimal sortRank) {
        this.sortRank = sortRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.STATUS
     *
     * @return the value of DEP.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.STATUS
     *
     * @param status the value for DEP.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.OPERATOR
     *
     * @return the value of DEP.OPERATOR
     *
     * @mbggenerated
     */
    public BigDecimal getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.OPERATOR
     *
     * @param operator the value for DEP.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(BigDecimal operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.OP_TIME
     *
     * @return the value of DEP.OP_TIME
     *
     * @mbggenerated
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.OP_TIME
     *
     * @param opTime the value for DEP.OP_TIME
     *
     * @mbggenerated
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.OPERATOR_NAME
     *
     * @return the value of DEP.OPERATOR_NAME
     *
     * @mbggenerated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.OPERATOR_NAME
     *
     * @param operatorName the value for DEP.OPERATOR_NAME
     *
     * @mbggenerated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP.DEP_REMARK
     *
     * @return the value of DEP.DEP_REMARK
     *
     * @mbggenerated
     */
    public String getDepRemark() {
        return depRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP.DEP_REMARK
     *
     * @param depRemark the value for DEP.DEP_REMARK
     *
     * @mbggenerated
     */
    public void setDepRemark(String depRemark) {
        this.depRemark = depRemark == null ? null : depRemark.trim();
    }

	public String getIsRecommend() {
		return isRecommend;
	}

	public void setIsRecommend(String isRecommend) {
		 this.isRecommend = isRecommend == null ? null : isRecommend.trim();
	}
}