package com.unique.plan.po;

import java.math.BigDecimal;
import java.util.Date;

public class HealthyTestPlanDet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET.PLAN_DET_ID
     *
     * @mbggenerated
     */
    private BigDecimal planDetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET.KPI_ID
     *
     * @mbggenerated
     */
    private BigDecimal kpiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET.TEST_TIME_ID
     *
     * @mbggenerated
     */
    private BigDecimal testTimeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET.PLAN_ID
     *
     * @mbggenerated
     */
    private BigDecimal planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET.TEST_BEGIN_TIME
     *
     * @mbggenerated
     */
    private Date testBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET.TEST_END_TIME
     *
     * @mbggenerated
     */
    private Date testEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET.ALERT_TIME
     *
     * @mbggenerated
     */
    private Date alertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET.ALERT_CON
     *
     * @mbggenerated
     */
    private String alertCon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET.PLAN_BEGIN_TIME
     *
     * @mbggenerated
     */
    private Date planBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET.PLAN_END_TIME
     *
     * @mbggenerated
     */
    private Date planEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET.REFERENCE_BEGIN
     *
     * @mbggenerated
     */
    private BigDecimal referenceBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET.REFERENCE_END
     *
     * @mbggenerated
     */
    private BigDecimal referenceEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET.PERIOD_VALUE
     *
     * @mbggenerated
     */
    private BigDecimal periodValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET.PERIOD_TYPE
     *
     * @mbggenerated
     */
    private BigDecimal periodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET.ALERT_RULE_ID
     *
     * @mbggenerated
     */
    private BigDecimal alertRuleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET.PLAN_DET_ID
     *
     * @return the value of HEALTHY_TEST_PLAN_DET.PLAN_DET_ID
     *
     * @mbggenerated
     */
    public BigDecimal getPlanDetId() {
        return planDetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET.PLAN_DET_ID
     *
     * @param planDetId the value for HEALTHY_TEST_PLAN_DET.PLAN_DET_ID
     *
     * @mbggenerated
     */
    public void setPlanDetId(BigDecimal planDetId) {
        this.planDetId = planDetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET.KPI_ID
     *
     * @return the value of HEALTHY_TEST_PLAN_DET.KPI_ID
     *
     * @mbggenerated
     */
    public BigDecimal getKpiId() {
        return kpiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET.KPI_ID
     *
     * @param kpiId the value for HEALTHY_TEST_PLAN_DET.KPI_ID
     *
     * @mbggenerated
     */
    public void setKpiId(BigDecimal kpiId) {
        this.kpiId = kpiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET.TEST_TIME_ID
     *
     * @return the value of HEALTHY_TEST_PLAN_DET.TEST_TIME_ID
     *
     * @mbggenerated
     */
    public BigDecimal getTestTimeId() {
        return testTimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET.TEST_TIME_ID
     *
     * @param testTimeId the value for HEALTHY_TEST_PLAN_DET.TEST_TIME_ID
     *
     * @mbggenerated
     */
    public void setTestTimeId(BigDecimal testTimeId) {
        this.testTimeId = testTimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET.PLAN_ID
     *
     * @return the value of HEALTHY_TEST_PLAN_DET.PLAN_ID
     *
     * @mbggenerated
     */
    public BigDecimal getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET.PLAN_ID
     *
     * @param planId the value for HEALTHY_TEST_PLAN_DET.PLAN_ID
     *
     * @mbggenerated
     */
    public void setPlanId(BigDecimal planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET.TEST_BEGIN_TIME
     *
     * @return the value of HEALTHY_TEST_PLAN_DET.TEST_BEGIN_TIME
     *
     * @mbggenerated
     */
    public Date getTestBeginTime() {
        return testBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET.TEST_BEGIN_TIME
     *
     * @param testBeginTime the value for HEALTHY_TEST_PLAN_DET.TEST_BEGIN_TIME
     *
     * @mbggenerated
     */
    public void setTestBeginTime(Date testBeginTime) {
        this.testBeginTime = testBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET.TEST_END_TIME
     *
     * @return the value of HEALTHY_TEST_PLAN_DET.TEST_END_TIME
     *
     * @mbggenerated
     */
    public Date getTestEndTime() {
        return testEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET.TEST_END_TIME
     *
     * @param testEndTime the value for HEALTHY_TEST_PLAN_DET.TEST_END_TIME
     *
     * @mbggenerated
     */
    public void setTestEndTime(Date testEndTime) {
        this.testEndTime = testEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET.ALERT_TIME
     *
     * @return the value of HEALTHY_TEST_PLAN_DET.ALERT_TIME
     *
     * @mbggenerated
     */
    public Date getAlertTime() {
        return alertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET.ALERT_TIME
     *
     * @param alertTime the value for HEALTHY_TEST_PLAN_DET.ALERT_TIME
     *
     * @mbggenerated
     */
    public void setAlertTime(Date alertTime) {
        this.alertTime = alertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET.ALERT_CON
     *
     * @return the value of HEALTHY_TEST_PLAN_DET.ALERT_CON
     *
     * @mbggenerated
     */
    public String getAlertCon() {
        return alertCon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET.ALERT_CON
     *
     * @param alertCon the value for HEALTHY_TEST_PLAN_DET.ALERT_CON
     *
     * @mbggenerated
     */
    public void setAlertCon(String alertCon) {
        this.alertCon = alertCon == null ? null : alertCon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET.PLAN_BEGIN_TIME
     *
     * @return the value of HEALTHY_TEST_PLAN_DET.PLAN_BEGIN_TIME
     *
     * @mbggenerated
     */
    public Date getPlanBeginTime() {
        return planBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET.PLAN_BEGIN_TIME
     *
     * @param planBeginTime the value for HEALTHY_TEST_PLAN_DET.PLAN_BEGIN_TIME
     *
     * @mbggenerated
     */
    public void setPlanBeginTime(Date planBeginTime) {
        this.planBeginTime = planBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET.PLAN_END_TIME
     *
     * @return the value of HEALTHY_TEST_PLAN_DET.PLAN_END_TIME
     *
     * @mbggenerated
     */
    public Date getPlanEndTime() {
        return planEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET.PLAN_END_TIME
     *
     * @param planEndTime the value for HEALTHY_TEST_PLAN_DET.PLAN_END_TIME
     *
     * @mbggenerated
     */
    public void setPlanEndTime(Date planEndTime) {
        this.planEndTime = planEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET.REFERENCE_BEGIN
     *
     * @return the value of HEALTHY_TEST_PLAN_DET.REFERENCE_BEGIN
     *
     * @mbggenerated
     */
    public BigDecimal getReferenceBegin() {
        return referenceBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET.REFERENCE_BEGIN
     *
     * @param referenceBegin the value for HEALTHY_TEST_PLAN_DET.REFERENCE_BEGIN
     *
     * @mbggenerated
     */
    public void setReferenceBegin(BigDecimal referenceBegin) {
        this.referenceBegin = referenceBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET.REFERENCE_END
     *
     * @return the value of HEALTHY_TEST_PLAN_DET.REFERENCE_END
     *
     * @mbggenerated
     */
    public BigDecimal getReferenceEnd() {
        return referenceEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET.REFERENCE_END
     *
     * @param referenceEnd the value for HEALTHY_TEST_PLAN_DET.REFERENCE_END
     *
     * @mbggenerated
     */
    public void setReferenceEnd(BigDecimal referenceEnd) {
        this.referenceEnd = referenceEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET.PERIOD_VALUE
     *
     * @return the value of HEALTHY_TEST_PLAN_DET.PERIOD_VALUE
     *
     * @mbggenerated
     */
    public BigDecimal getPeriodValue() {
        return periodValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET.PERIOD_VALUE
     *
     * @param periodValue the value for HEALTHY_TEST_PLAN_DET.PERIOD_VALUE
     *
     * @mbggenerated
     */
    public void setPeriodValue(BigDecimal periodValue) {
        this.periodValue = periodValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET.PERIOD_TYPE
     *
     * @return the value of HEALTHY_TEST_PLAN_DET.PERIOD_TYPE
     *
     * @mbggenerated
     */
    public BigDecimal getPeriodType() {
        return periodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET.PERIOD_TYPE
     *
     * @param periodType the value for HEALTHY_TEST_PLAN_DET.PERIOD_TYPE
     *
     * @mbggenerated
     */
    public void setPeriodType(BigDecimal periodType) {
        this.periodType = periodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET.ALERT_RULE_ID
     *
     * @return the value of HEALTHY_TEST_PLAN_DET.ALERT_RULE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getAlertRuleId() {
        return alertRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET.ALERT_RULE_ID
     *
     * @param alertRuleId the value for HEALTHY_TEST_PLAN_DET.ALERT_RULE_ID
     *
     * @mbggenerated
     */
    public void setAlertRuleId(BigDecimal alertRuleId) {
        this.alertRuleId = alertRuleId;
    }
}