package com.unique.plan.po;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class HealthyTestPlanTemplateDet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.TEMPLETE_DET_ID
     *
     * @mbggenerated
     */
    private BigDecimal templeteDetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.KPI_ID
     *
     * @mbggenerated
     */
    private BigDecimal kpiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.TEST_TIME_ID
     *
     * @mbggenerated
     */
    private BigDecimal testTimeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.ALERT_RULE_ID
     *
     * @mbggenerated
     */
    private BigDecimal alertRuleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.TEST_TEMPLATE_ID
     *
     * @mbggenerated
     */
    private BigDecimal testTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.PLAN_BEGIN_TIME
     *
     * @mbggenerated
     */
    private Date planBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.PLAN_END_TIME
     *
     * @mbggenerated
     */
    private Date planEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.ALERT_TIME
     *
     * @mbggenerated
     */
    private Date alertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.ALERT_CON
     *
     * @mbggenerated
     */
    private String alertCon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.TEST_BEGIN_TIME
     *
     * @mbggenerated
     */
    private Date testBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.TEST_END_TIME
     *
     * @mbggenerated
     */
    private Date testEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.PERIOD_TYPE
     *
     * @mbggenerated
     */
    private BigDecimal periodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.PERIOD_VALUE
     *
     * @mbggenerated
     */
    private BigDecimal periodValue;

    public String getTestTimeName() {
		return testTimeName;
	}

	public void setTestTimeName(String testTimeName) {
		this.testTimeName = testTimeName;
	}

	public String getBeginTime() {
		return beginTime;
	}

	public void setBeginTime(String beginTime) {
		this.beginTime = beginTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	private String testTimeName;
    private String beginTime;
    private String endTime;
    
    
    private List<TestPlanTemplateDetRule> testPlanTemplateDetRules;
    public List<TestPlanTemplateDetRule> getTestPlanTemplateDetRules() {
		return testPlanTemplateDetRules;
	}

	public void setTestPlanTemplateDetRules(
			List<TestPlanTemplateDetRule> testPlanTemplateDetRules) {
		this.testPlanTemplateDetRules = testPlanTemplateDetRules;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.TEMPLETE_DET_ID
     *
     * @return the value of HEALTHY_TEST_PLAN_TEMPLATE_DET.TEMPLETE_DET_ID
     *
     * @mbggenerated
     */
    public BigDecimal getTempleteDetId() {
        return templeteDetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.TEMPLETE_DET_ID
     *
     * @param templeteDetId the value for HEALTHY_TEST_PLAN_TEMPLATE_DET.TEMPLETE_DET_ID
     *
     * @mbggenerated
     */
    public void setTempleteDetId(BigDecimal templeteDetId) {
        this.templeteDetId = templeteDetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.KPI_ID
     *
     * @return the value of HEALTHY_TEST_PLAN_TEMPLATE_DET.KPI_ID
     *
     * @mbggenerated
     */
    public BigDecimal getKpiId() {
        return kpiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.KPI_ID
     *
     * @param kpiId the value for HEALTHY_TEST_PLAN_TEMPLATE_DET.KPI_ID
     *
     * @mbggenerated
     */
    public void setKpiId(BigDecimal kpiId) {
        this.kpiId = kpiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.TEST_TIME_ID
     *
     * @return the value of HEALTHY_TEST_PLAN_TEMPLATE_DET.TEST_TIME_ID
     *
     * @mbggenerated
     */
    public BigDecimal getTestTimeId() {
        return testTimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.TEST_TIME_ID
     *
     * @param testTimeId the value for HEALTHY_TEST_PLAN_TEMPLATE_DET.TEST_TIME_ID
     *
     * @mbggenerated
     */
    public void setTestTimeId(BigDecimal testTimeId) {
        this.testTimeId = testTimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.ALERT_RULE_ID
     *
     * @return the value of HEALTHY_TEST_PLAN_TEMPLATE_DET.ALERT_RULE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getAlertRuleId() {
        return alertRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.ALERT_RULE_ID
     *
     * @param alertRuleId the value for HEALTHY_TEST_PLAN_TEMPLATE_DET.ALERT_RULE_ID
     *
     * @mbggenerated
     */
    public void setAlertRuleId(BigDecimal alertRuleId) {
        this.alertRuleId = alertRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.TEST_TEMPLATE_ID
     *
     * @return the value of HEALTHY_TEST_PLAN_TEMPLATE_DET.TEST_TEMPLATE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getTestTemplateId() {
        return testTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.TEST_TEMPLATE_ID
     *
     * @param testTemplateId the value for HEALTHY_TEST_PLAN_TEMPLATE_DET.TEST_TEMPLATE_ID
     *
     * @mbggenerated
     */
    public void setTestTemplateId(BigDecimal testTemplateId) {
        this.testTemplateId = testTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.PLAN_BEGIN_TIME
     *
     * @return the value of HEALTHY_TEST_PLAN_TEMPLATE_DET.PLAN_BEGIN_TIME
     *
     * @mbggenerated
     */
    public Date getPlanBeginTime() {
        return planBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.PLAN_BEGIN_TIME
     *
     * @param planBeginTime the value for HEALTHY_TEST_PLAN_TEMPLATE_DET.PLAN_BEGIN_TIME
     *
     * @mbggenerated
     */
    public void setPlanBeginTime(Date planBeginTime) {
        this.planBeginTime = planBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.PLAN_END_TIME
     *
     * @return the value of HEALTHY_TEST_PLAN_TEMPLATE_DET.PLAN_END_TIME
     *
     * @mbggenerated
     */
    public Date getPlanEndTime() {
        return planEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.PLAN_END_TIME
     *
     * @param planEndTime the value for HEALTHY_TEST_PLAN_TEMPLATE_DET.PLAN_END_TIME
     *
     * @mbggenerated
     */
    public void setPlanEndTime(Date planEndTime) {
        this.planEndTime = planEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.ALERT_TIME
     *
     * @return the value of HEALTHY_TEST_PLAN_TEMPLATE_DET.ALERT_TIME
     *
     * @mbggenerated
     */
    public Date getAlertTime() {
        return alertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.ALERT_TIME
     *
     * @param alertTime the value for HEALTHY_TEST_PLAN_TEMPLATE_DET.ALERT_TIME
     *
     * @mbggenerated
     */
    public void setAlertTime(Date alertTime) {
        this.alertTime = alertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.ALERT_CON
     *
     * @return the value of HEALTHY_TEST_PLAN_TEMPLATE_DET.ALERT_CON
     *
     * @mbggenerated
     */
    public String getAlertCon() {
        return alertCon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.ALERT_CON
     *
     * @param alertCon the value for HEALTHY_TEST_PLAN_TEMPLATE_DET.ALERT_CON
     *
     * @mbggenerated
     */
    public void setAlertCon(String alertCon) {
        this.alertCon = alertCon == null ? null : alertCon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.TEST_BEGIN_TIME
     *
     * @return the value of HEALTHY_TEST_PLAN_TEMPLATE_DET.TEST_BEGIN_TIME
     *
     * @mbggenerated
     */
    public Date getTestBeginTime() {
        return testBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.TEST_BEGIN_TIME
     *
     * @param testBeginTime the value for HEALTHY_TEST_PLAN_TEMPLATE_DET.TEST_BEGIN_TIME
     *
     * @mbggenerated
     */
    public void setTestBeginTime(Date testBeginTime) {
        this.testBeginTime = testBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.TEST_END_TIME
     *
     * @return the value of HEALTHY_TEST_PLAN_TEMPLATE_DET.TEST_END_TIME
     *
     * @mbggenerated
     */
    public Date getTestEndTime() {
        return testEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.TEST_END_TIME
     *
     * @param testEndTime the value for HEALTHY_TEST_PLAN_TEMPLATE_DET.TEST_END_TIME
     *
     * @mbggenerated
     */
    public void setTestEndTime(Date testEndTime) {
        this.testEndTime = testEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.PERIOD_TYPE
     *
     * @return the value of HEALTHY_TEST_PLAN_TEMPLATE_DET.PERIOD_TYPE
     *
     * @mbggenerated
     */
    public BigDecimal getPeriodType() {
        return periodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.PERIOD_TYPE
     *
     * @param periodType the value for HEALTHY_TEST_PLAN_TEMPLATE_DET.PERIOD_TYPE
     *
     * @mbggenerated
     */
    public void setPeriodType(BigDecimal periodType) {
        this.periodType = periodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.PERIOD_VALUE
     *
     * @return the value of HEALTHY_TEST_PLAN_TEMPLATE_DET.PERIOD_VALUE
     *
     * @mbggenerated
     */
    public BigDecimal getPeriodValue() {
        return periodValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_TEMPLATE_DET.PERIOD_VALUE
     *
     * @param periodValue the value for HEALTHY_TEST_PLAN_TEMPLATE_DET.PERIOD_VALUE
     *
     * @mbggenerated
     */
    public void setPeriodValue(BigDecimal periodValue) {
        this.periodValue = periodValue;
    }
}