package com.unique.plan.po;

import java.math.BigDecimal;

public class HealthyTestPlanDetRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET_RULE.PLAN_RULE_ID
     *
     * @mbggenerated
     */
    private BigDecimal planRuleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET_RULE.PLAN_ID
     *
     * @mbggenerated
     */
    private BigDecimal planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET_RULE.USER_ID
     *
     * @mbggenerated
     */
    private BigDecimal userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET_RULE.PLAN_DET_ID
     *
     * @mbggenerated
     */
    private BigDecimal planDetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET_RULE.KPI_ID
     *
     * @mbggenerated
     */
    private BigDecimal kpiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET_RULE.ONE_BEGIN_VALUE
     *
     * @mbggenerated
     */
    private BigDecimal oneBeginValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET_RULE.ONE_BEGIN_SYMBOL
     *
     * @mbggenerated
     */
    private String oneBeginSymbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET_RULE.ONE_KPI_ID
     *
     * @mbggenerated
     */
    private BigDecimal oneKpiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET_RULE.ONE_END_SYMBOL
     *
     * @mbggenerated
     */
    private String oneEndSymbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET_RULE.ONE_END_VALUE
     *
     * @mbggenerated
     */
    private BigDecimal oneEndValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET_RULE.ONE_TWO_RELATION
     *
     * @mbggenerated
     */
    private String oneTwoRelation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET_RULE.TWO_BEGIN_VALUE
     *
     * @mbggenerated
     */
    private BigDecimal twoBeginValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET_RULE.TWO_BEGIN_SYMBOL
     *
     * @mbggenerated
     */
    private String twoBeginSymbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET_RULE.TWO_KPI_ID
     *
     * @mbggenerated
     */
    private BigDecimal twoKpiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET_RULE.TWO_END_SYMBOL
     *
     * @mbggenerated
     */
    private String twoEndSymbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET_RULE.TWO_END_VALUE
     *
     * @mbggenerated
     */
    private BigDecimal twoEndValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET_RULE.ALERT_GRADE
     *
     * @mbggenerated
     */
    private BigDecimal alertGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET_RULE.DOCTOR_ALERT_CON
     *
     * @mbggenerated
     */
    private String doctorAlertCon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET_RULE.USER_ALERT_RESULT
     *
     * @mbggenerated
     */
    private String userAlertResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_DET_RULE.USER_HEALTHY_SUGGEST
     *
     * @mbggenerated
     */
    private String userHealthySuggest;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET_RULE.PLAN_RULE_ID
     *
     * @return the value of HEALTHY_TEST_PLAN_DET_RULE.PLAN_RULE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getPlanRuleId() {
        return planRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET_RULE.PLAN_RULE_ID
     *
     * @param planRuleId the value for HEALTHY_TEST_PLAN_DET_RULE.PLAN_RULE_ID
     *
     * @mbggenerated
     */
    public void setPlanRuleId(BigDecimal planRuleId) {
        this.planRuleId = planRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET_RULE.PLAN_ID
     *
     * @return the value of HEALTHY_TEST_PLAN_DET_RULE.PLAN_ID
     *
     * @mbggenerated
     */
    public BigDecimal getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET_RULE.PLAN_ID
     *
     * @param planId the value for HEALTHY_TEST_PLAN_DET_RULE.PLAN_ID
     *
     * @mbggenerated
     */
    public void setPlanId(BigDecimal planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET_RULE.USER_ID
     *
     * @return the value of HEALTHY_TEST_PLAN_DET_RULE.USER_ID
     *
     * @mbggenerated
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET_RULE.USER_ID
     *
     * @param userId the value for HEALTHY_TEST_PLAN_DET_RULE.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET_RULE.PLAN_DET_ID
     *
     * @return the value of HEALTHY_TEST_PLAN_DET_RULE.PLAN_DET_ID
     *
     * @mbggenerated
     */
    public BigDecimal getPlanDetId() {
        return planDetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET_RULE.PLAN_DET_ID
     *
     * @param planDetId the value for HEALTHY_TEST_PLAN_DET_RULE.PLAN_DET_ID
     *
     * @mbggenerated
     */
    public void setPlanDetId(BigDecimal planDetId) {
        this.planDetId = planDetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET_RULE.KPI_ID
     *
     * @return the value of HEALTHY_TEST_PLAN_DET_RULE.KPI_ID
     *
     * @mbggenerated
     */
    public BigDecimal getKpiId() {
        return kpiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET_RULE.KPI_ID
     *
     * @param kpiId the value for HEALTHY_TEST_PLAN_DET_RULE.KPI_ID
     *
     * @mbggenerated
     */
    public void setKpiId(BigDecimal kpiId) {
        this.kpiId = kpiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET_RULE.ONE_BEGIN_VALUE
     *
     * @return the value of HEALTHY_TEST_PLAN_DET_RULE.ONE_BEGIN_VALUE
     *
     * @mbggenerated
     */
    public BigDecimal getOneBeginValue() {
        return oneBeginValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET_RULE.ONE_BEGIN_VALUE
     *
     * @param oneBeginValue the value for HEALTHY_TEST_PLAN_DET_RULE.ONE_BEGIN_VALUE
     *
     * @mbggenerated
     */
    public void setOneBeginValue(BigDecimal oneBeginValue) {
        this.oneBeginValue = oneBeginValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET_RULE.ONE_BEGIN_SYMBOL
     *
     * @return the value of HEALTHY_TEST_PLAN_DET_RULE.ONE_BEGIN_SYMBOL
     *
     * @mbggenerated
     */
    public String getOneBeginSymbol() {
        return oneBeginSymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET_RULE.ONE_BEGIN_SYMBOL
     *
     * @param oneBeginSymbol the value for HEALTHY_TEST_PLAN_DET_RULE.ONE_BEGIN_SYMBOL
     *
     * @mbggenerated
     */
    public void setOneBeginSymbol(String oneBeginSymbol) {
        this.oneBeginSymbol = oneBeginSymbol == null ? null : oneBeginSymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET_RULE.ONE_KPI_ID
     *
     * @return the value of HEALTHY_TEST_PLAN_DET_RULE.ONE_KPI_ID
     *
     * @mbggenerated
     */
    public BigDecimal getOneKpiId() {
        return oneKpiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET_RULE.ONE_KPI_ID
     *
     * @param oneKpiId the value for HEALTHY_TEST_PLAN_DET_RULE.ONE_KPI_ID
     *
     * @mbggenerated
     */
    public void setOneKpiId(BigDecimal oneKpiId) {
        this.oneKpiId = oneKpiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET_RULE.ONE_END_SYMBOL
     *
     * @return the value of HEALTHY_TEST_PLAN_DET_RULE.ONE_END_SYMBOL
     *
     * @mbggenerated
     */
    public String getOneEndSymbol() {
        return oneEndSymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET_RULE.ONE_END_SYMBOL
     *
     * @param oneEndSymbol the value for HEALTHY_TEST_PLAN_DET_RULE.ONE_END_SYMBOL
     *
     * @mbggenerated
     */
    public void setOneEndSymbol(String oneEndSymbol) {
        this.oneEndSymbol = oneEndSymbol == null ? null : oneEndSymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET_RULE.ONE_END_VALUE
     *
     * @return the value of HEALTHY_TEST_PLAN_DET_RULE.ONE_END_VALUE
     *
     * @mbggenerated
     */
    public BigDecimal getOneEndValue() {
        return oneEndValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET_RULE.ONE_END_VALUE
     *
     * @param oneEndValue the value for HEALTHY_TEST_PLAN_DET_RULE.ONE_END_VALUE
     *
     * @mbggenerated
     */
    public void setOneEndValue(BigDecimal oneEndValue) {
        this.oneEndValue = oneEndValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET_RULE.ONE_TWO_RELATION
     *
     * @return the value of HEALTHY_TEST_PLAN_DET_RULE.ONE_TWO_RELATION
     *
     * @mbggenerated
     */
    public String getOneTwoRelation() {
        return oneTwoRelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET_RULE.ONE_TWO_RELATION
     *
     * @param oneTwoRelation the value for HEALTHY_TEST_PLAN_DET_RULE.ONE_TWO_RELATION
     *
     * @mbggenerated
     */
    public void setOneTwoRelation(String oneTwoRelation) {
        this.oneTwoRelation = oneTwoRelation == null ? null : oneTwoRelation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET_RULE.TWO_BEGIN_VALUE
     *
     * @return the value of HEALTHY_TEST_PLAN_DET_RULE.TWO_BEGIN_VALUE
     *
     * @mbggenerated
     */
    public BigDecimal getTwoBeginValue() {
        return twoBeginValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET_RULE.TWO_BEGIN_VALUE
     *
     * @param twoBeginValue the value for HEALTHY_TEST_PLAN_DET_RULE.TWO_BEGIN_VALUE
     *
     * @mbggenerated
     */
    public void setTwoBeginValue(BigDecimal twoBeginValue) {
        this.twoBeginValue = twoBeginValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET_RULE.TWO_BEGIN_SYMBOL
     *
     * @return the value of HEALTHY_TEST_PLAN_DET_RULE.TWO_BEGIN_SYMBOL
     *
     * @mbggenerated
     */
    public String getTwoBeginSymbol() {
        return twoBeginSymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET_RULE.TWO_BEGIN_SYMBOL
     *
     * @param twoBeginSymbol the value for HEALTHY_TEST_PLAN_DET_RULE.TWO_BEGIN_SYMBOL
     *
     * @mbggenerated
     */
    public void setTwoBeginSymbol(String twoBeginSymbol) {
        this.twoBeginSymbol = twoBeginSymbol == null ? null : twoBeginSymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET_RULE.TWO_KPI_ID
     *
     * @return the value of HEALTHY_TEST_PLAN_DET_RULE.TWO_KPI_ID
     *
     * @mbggenerated
     */
    public BigDecimal getTwoKpiId() {
        return twoKpiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET_RULE.TWO_KPI_ID
     *
     * @param twoKpiId the value for HEALTHY_TEST_PLAN_DET_RULE.TWO_KPI_ID
     *
     * @mbggenerated
     */
    public void setTwoKpiId(BigDecimal twoKpiId) {
        this.twoKpiId = twoKpiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET_RULE.TWO_END_SYMBOL
     *
     * @return the value of HEALTHY_TEST_PLAN_DET_RULE.TWO_END_SYMBOL
     *
     * @mbggenerated
     */
    public String getTwoEndSymbol() {
        return twoEndSymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET_RULE.TWO_END_SYMBOL
     *
     * @param twoEndSymbol the value for HEALTHY_TEST_PLAN_DET_RULE.TWO_END_SYMBOL
     *
     * @mbggenerated
     */
    public void setTwoEndSymbol(String twoEndSymbol) {
        this.twoEndSymbol = twoEndSymbol == null ? null : twoEndSymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET_RULE.TWO_END_VALUE
     *
     * @return the value of HEALTHY_TEST_PLAN_DET_RULE.TWO_END_VALUE
     *
     * @mbggenerated
     */
    public BigDecimal getTwoEndValue() {
        return twoEndValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET_RULE.TWO_END_VALUE
     *
     * @param twoEndValue the value for HEALTHY_TEST_PLAN_DET_RULE.TWO_END_VALUE
     *
     * @mbggenerated
     */
    public void setTwoEndValue(BigDecimal twoEndValue) {
        this.twoEndValue = twoEndValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET_RULE.ALERT_GRADE
     *
     * @return the value of HEALTHY_TEST_PLAN_DET_RULE.ALERT_GRADE
     *
     * @mbggenerated
     */
    public BigDecimal getAlertGrade() {
        return alertGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET_RULE.ALERT_GRADE
     *
     * @param alertGrade the value for HEALTHY_TEST_PLAN_DET_RULE.ALERT_GRADE
     *
     * @mbggenerated
     */
    public void setAlertGrade(BigDecimal alertGrade) {
        this.alertGrade = alertGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET_RULE.DOCTOR_ALERT_CON
     *
     * @return the value of HEALTHY_TEST_PLAN_DET_RULE.DOCTOR_ALERT_CON
     *
     * @mbggenerated
     */
    public String getDoctorAlertCon() {
        return doctorAlertCon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET_RULE.DOCTOR_ALERT_CON
     *
     * @param doctorAlertCon the value for HEALTHY_TEST_PLAN_DET_RULE.DOCTOR_ALERT_CON
     *
     * @mbggenerated
     */
    public void setDoctorAlertCon(String doctorAlertCon) {
        this.doctorAlertCon = doctorAlertCon == null ? null : doctorAlertCon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET_RULE.USER_ALERT_RESULT
     *
     * @return the value of HEALTHY_TEST_PLAN_DET_RULE.USER_ALERT_RESULT
     *
     * @mbggenerated
     */
    public String getUserAlertResult() {
        return userAlertResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET_RULE.USER_ALERT_RESULT
     *
     * @param userAlertResult the value for HEALTHY_TEST_PLAN_DET_RULE.USER_ALERT_RESULT
     *
     * @mbggenerated
     */
    public void setUserAlertResult(String userAlertResult) {
        this.userAlertResult = userAlertResult == null ? null : userAlertResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_DET_RULE.USER_HEALTHY_SUGGEST
     *
     * @return the value of HEALTHY_TEST_PLAN_DET_RULE.USER_HEALTHY_SUGGEST
     *
     * @mbggenerated
     */
    public String getUserHealthySuggest() {
        return userHealthySuggest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_DET_RULE.USER_HEALTHY_SUGGEST
     *
     * @param userHealthySuggest the value for HEALTHY_TEST_PLAN_DET_RULE.USER_HEALTHY_SUGGEST
     *
     * @mbggenerated
     */
    public void setUserHealthySuggest(String userHealthySuggest) {
        this.userHealthySuggest = userHealthySuggest == null ? null : userHealthySuggest.trim();
    }
}