package com.unique.plan.po;

import java.math.BigDecimal;
import java.util.Date;

public class HealthyTestPlanTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_TEMPLATE.TEST_TEMPLATE_ID
     *
     * @mbggenerated
     */
    private BigDecimal testTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_TEMPLATE.STAFF_ID
     *
     * @mbggenerated
     */
    private BigDecimal staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_TEMPLATE.DEP_ID
     *
     * @mbggenerated
     */
    private BigDecimal depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_TEMPLATE.ORG_ID
     *
     * @mbggenerated
     */
    private BigDecimal orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_TEMPLATE.TEMPLATE_NAME
     *
     * @mbggenerated
     */
    private String templateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_TEMPLATE.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_TEMPLATE.OP_TIME
     *
     * @mbggenerated
     */
    private Date opTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_TEMPLATE.OPEATOR
     *
     * @mbggenerated
     */
    private BigDecimal opeator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEALTHY_TEST_PLAN_TEMPLATE.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_TEMPLATE.TEST_TEMPLATE_ID
     *
     * @return the value of HEALTHY_TEST_PLAN_TEMPLATE.TEST_TEMPLATE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getTestTemplateId() {
        return testTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_TEMPLATE.TEST_TEMPLATE_ID
     *
     * @param testTemplateId the value for HEALTHY_TEST_PLAN_TEMPLATE.TEST_TEMPLATE_ID
     *
     * @mbggenerated
     */
    public void setTestTemplateId(BigDecimal testTemplateId) {
        this.testTemplateId = testTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_TEMPLATE.STAFF_ID
     *
     * @return the value of HEALTHY_TEST_PLAN_TEMPLATE.STAFF_ID
     *
     * @mbggenerated
     */
    public BigDecimal getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_TEMPLATE.STAFF_ID
     *
     * @param staffId the value for HEALTHY_TEST_PLAN_TEMPLATE.STAFF_ID
     *
     * @mbggenerated
     */
    public void setStaffId(BigDecimal staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_TEMPLATE.DEP_ID
     *
     * @return the value of HEALTHY_TEST_PLAN_TEMPLATE.DEP_ID
     *
     * @mbggenerated
     */
    public BigDecimal getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_TEMPLATE.DEP_ID
     *
     * @param depId the value for HEALTHY_TEST_PLAN_TEMPLATE.DEP_ID
     *
     * @mbggenerated
     */
    public void setDepId(BigDecimal depId) {
        this.depId = depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_TEMPLATE.ORG_ID
     *
     * @return the value of HEALTHY_TEST_PLAN_TEMPLATE.ORG_ID
     *
     * @mbggenerated
     */
    public BigDecimal getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_TEMPLATE.ORG_ID
     *
     * @param orgId the value for HEALTHY_TEST_PLAN_TEMPLATE.ORG_ID
     *
     * @mbggenerated
     */
    public void setOrgId(BigDecimal orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_TEMPLATE.TEMPLATE_NAME
     *
     * @return the value of HEALTHY_TEST_PLAN_TEMPLATE.TEMPLATE_NAME
     *
     * @mbggenerated
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_TEMPLATE.TEMPLATE_NAME
     *
     * @param templateName the value for HEALTHY_TEST_PLAN_TEMPLATE.TEMPLATE_NAME
     *
     * @mbggenerated
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_TEMPLATE.CREATE_TIME
     *
     * @return the value of HEALTHY_TEST_PLAN_TEMPLATE.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_TEMPLATE.CREATE_TIME
     *
     * @param createTime the value for HEALTHY_TEST_PLAN_TEMPLATE.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_TEMPLATE.OP_TIME
     *
     * @return the value of HEALTHY_TEST_PLAN_TEMPLATE.OP_TIME
     *
     * @mbggenerated
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_TEMPLATE.OP_TIME
     *
     * @param opTime the value for HEALTHY_TEST_PLAN_TEMPLATE.OP_TIME
     *
     * @mbggenerated
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_TEMPLATE.OPEATOR
     *
     * @return the value of HEALTHY_TEST_PLAN_TEMPLATE.OPEATOR
     *
     * @mbggenerated
     */
    public BigDecimal getOpeator() {
        return opeator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_TEMPLATE.OPEATOR
     *
     * @param opeator the value for HEALTHY_TEST_PLAN_TEMPLATE.OPEATOR
     *
     * @mbggenerated
     */
    public void setOpeator(BigDecimal opeator) {
        this.opeator = opeator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEALTHY_TEST_PLAN_TEMPLATE.STATUS
     *
     * @return the value of HEALTHY_TEST_PLAN_TEMPLATE.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEALTHY_TEST_PLAN_TEMPLATE.STATUS
     *
     * @param status the value for HEALTHY_TEST_PLAN_TEMPLATE.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}