package com.unique.reg.po;

import java.math.BigDecimal;
import java.util.Date;

public class Billing {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLING.BILLING_ID
     *
     * @mbggenerated
     */
    private BigDecimal billingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLING.BILL_TYPE_ID
     *
     * @mbggenerated
     */
    private BigDecimal billTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLING.SRC_ID
     *
     * @mbggenerated
     */
    private BigDecimal srcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLING.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLING.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLING.OPERATOR
     *
     * @mbggenerated
     */
    private BigDecimal operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLING.OP_TIME
     *
     * @mbggenerated
     */
    private Date opTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLING.OPERATOR_NAME
     *
     * @mbggenerated
     */
    private Object operatorName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLING.BILLING_ID
     *
     * @return the value of BILLING.BILLING_ID
     *
     * @mbggenerated
     */
    public BigDecimal getBillingId() {
        return billingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLING.BILLING_ID
     *
     * @param billingId the value for BILLING.BILLING_ID
     *
     * @mbggenerated
     */
    public void setBillingId(BigDecimal billingId) {
        this.billingId = billingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLING.BILL_TYPE_ID
     *
     * @return the value of BILLING.BILL_TYPE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getBillTypeId() {
        return billTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLING.BILL_TYPE_ID
     *
     * @param billTypeId the value for BILLING.BILL_TYPE_ID
     *
     * @mbggenerated
     */
    public void setBillTypeId(BigDecimal billTypeId) {
        this.billTypeId = billTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLING.SRC_ID
     *
     * @return the value of BILLING.SRC_ID
     *
     * @mbggenerated
     */
    public BigDecimal getSrcId() {
        return srcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLING.SRC_ID
     *
     * @param srcId the value for BILLING.SRC_ID
     *
     * @mbggenerated
     */
    public void setSrcId(BigDecimal srcId) {
        this.srcId = srcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLING.CREATE_TIME
     *
     * @return the value of BILLING.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLING.CREATE_TIME
     *
     * @param createTime the value for BILLING.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLING.STATUS
     *
     * @return the value of BILLING.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLING.STATUS
     *
     * @param status the value for BILLING.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLING.OPERATOR
     *
     * @return the value of BILLING.OPERATOR
     *
     * @mbggenerated
     */
    public BigDecimal getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLING.OPERATOR
     *
     * @param operator the value for BILLING.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(BigDecimal operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLING.OP_TIME
     *
     * @return the value of BILLING.OP_TIME
     *
     * @mbggenerated
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLING.OP_TIME
     *
     * @param opTime the value for BILLING.OP_TIME
     *
     * @mbggenerated
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLING.OPERATOR_NAME
     *
     * @return the value of BILLING.OPERATOR_NAME
     *
     * @mbggenerated
     */
    public Object getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLING.OPERATOR_NAME
     *
     * @param operatorName the value for BILLING.OPERATOR_NAME
     *
     * @mbggenerated
     */
    public void setOperatorName(Object operatorName) {
        this.operatorName = operatorName;
    }
}