package com.unique.reg.po;

import java.math.BigDecimal;
import java.util.Date;

public class BillDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILL_DETAIL.BILL_DETAIL_ID
     *
     * @mbggenerated
     */
    private BigDecimal billDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILL_DETAIL.BILLING_ID
     *
     * @mbggenerated
     */
    private BigDecimal billingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILL_DETAIL.PRODUCTPRICE
     *
     * @mbggenerated
     */
    private BigDecimal productprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILL_DETAIL.FEE_MONEY
     *
     * @mbggenerated
     */
    private BigDecimal feeMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILL_DETAIL.FEE_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal feeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILL_DETAIL.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILL_DETAIL.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILL_DETAIL.OPERATOR
     *
     * @mbggenerated
     */
    private BigDecimal operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILL_DETAIL.OP_TIME
     *
     * @mbggenerated
     */
    private Date opTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILL_DETAIL.OPERATE_TYPE
     *
     * @mbggenerated
     */
    private String operateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILL_DETAIL.OPERATE_ORG_CODE
     *
     * @mbggenerated
     */
    private String operateOrgCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILL_DETAIL.BILL_DETAIL_ID
     *
     * @return the value of BILL_DETAIL.BILL_DETAIL_ID
     *
     * @mbggenerated
     */
    public BigDecimal getBillDetailId() {
        return billDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILL_DETAIL.BILL_DETAIL_ID
     *
     * @param billDetailId the value for BILL_DETAIL.BILL_DETAIL_ID
     *
     * @mbggenerated
     */
    public void setBillDetailId(BigDecimal billDetailId) {
        this.billDetailId = billDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILL_DETAIL.BILLING_ID
     *
     * @return the value of BILL_DETAIL.BILLING_ID
     *
     * @mbggenerated
     */
    public BigDecimal getBillingId() {
        return billingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILL_DETAIL.BILLING_ID
     *
     * @param billingId the value for BILL_DETAIL.BILLING_ID
     *
     * @mbggenerated
     */
    public void setBillingId(BigDecimal billingId) {
        this.billingId = billingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILL_DETAIL.PRODUCTPRICE
     *
     * @return the value of BILL_DETAIL.PRODUCTPRICE
     *
     * @mbggenerated
     */
    public BigDecimal getProductprice() {
        return productprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILL_DETAIL.PRODUCTPRICE
     *
     * @param productprice the value for BILL_DETAIL.PRODUCTPRICE
     *
     * @mbggenerated
     */
    public void setProductprice(BigDecimal productprice) {
        this.productprice = productprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILL_DETAIL.FEE_MONEY
     *
     * @return the value of BILL_DETAIL.FEE_MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getFeeMoney() {
        return feeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILL_DETAIL.FEE_MONEY
     *
     * @param feeMoney the value for BILL_DETAIL.FEE_MONEY
     *
     * @mbggenerated
     */
    public void setFeeMoney(BigDecimal feeMoney) {
        this.feeMoney = feeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILL_DETAIL.FEE_AMOUNT
     *
     * @return the value of BILL_DETAIL.FEE_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getFeeAmount() {
        return feeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILL_DETAIL.FEE_AMOUNT
     *
     * @param feeAmount the value for BILL_DETAIL.FEE_AMOUNT
     *
     * @mbggenerated
     */
    public void setFeeAmount(BigDecimal feeAmount) {
        this.feeAmount = feeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILL_DETAIL.CREATE_TIME
     *
     * @return the value of BILL_DETAIL.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILL_DETAIL.CREATE_TIME
     *
     * @param createTime the value for BILL_DETAIL.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILL_DETAIL.STATUS
     *
     * @return the value of BILL_DETAIL.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILL_DETAIL.STATUS
     *
     * @param status the value for BILL_DETAIL.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILL_DETAIL.OPERATOR
     *
     * @return the value of BILL_DETAIL.OPERATOR
     *
     * @mbggenerated
     */
    public BigDecimal getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILL_DETAIL.OPERATOR
     *
     * @param operator the value for BILL_DETAIL.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(BigDecimal operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILL_DETAIL.OP_TIME
     *
     * @return the value of BILL_DETAIL.OP_TIME
     *
     * @mbggenerated
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILL_DETAIL.OP_TIME
     *
     * @param opTime the value for BILL_DETAIL.OP_TIME
     *
     * @mbggenerated
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILL_DETAIL.OPERATE_TYPE
     *
     * @return the value of BILL_DETAIL.OPERATE_TYPE
     *
     * @mbggenerated
     */
    public String getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILL_DETAIL.OPERATE_TYPE
     *
     * @param operateType the value for BILL_DETAIL.OPERATE_TYPE
     *
     * @mbggenerated
     */
    public void setOperateType(String operateType) {
        this.operateType = operateType == null ? null : operateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILL_DETAIL.OPERATE_ORG_CODE
     *
     * @return the value of BILL_DETAIL.OPERATE_ORG_CODE
     *
     * @mbggenerated
     */
    public String getOperateOrgCode() {
        return operateOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILL_DETAIL.OPERATE_ORG_CODE
     *
     * @param operateOrgCode the value for BILL_DETAIL.OPERATE_ORG_CODE
     *
     * @mbggenerated
     */
    public void setOperateOrgCode(String operateOrgCode) {
        this.operateOrgCode = operateOrgCode == null ? null : operateOrgCode.trim();
    }
}