package com.unique.reg.po;

import java.math.BigDecimal;
import java.util.Date;

public class McReg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.REG_ID
     *
     * @mbggenerated
     */
    private BigDecimal regId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.ORG_ID
     *
     * @mbggenerated
     */
    private BigDecimal orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.DUTY_ID
     *
     * @mbggenerated
     */
    private BigDecimal dutyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.DEP_ID
     *
     * @mbggenerated
     */
    private BigDecimal depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.STAFF_ID
     *
     * @mbggenerated
     */
    private BigDecimal staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.PERIOD_ID
     *
     * @mbggenerated
     */
    private BigDecimal periodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.REG_WAY_NAME
     *
     * @mbggenerated
     */
    private String regWayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.PAY_WAY_NAME
     *
     * @mbggenerated
     */
    private String payWayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.ORDER_TIME
     *
     * @mbggenerated
     */
    private Date orderTime;

    ///就诊精确时间
    private String pickupAddr;
    private BigDecimal age;
    private BigDecimal friendId;

    private BigDecimal orderId;
    private BigDecimal orderMoney;//订单金额
    private String orderNo;//订单编号
    
    
    private String cardNo;			//卡号
    private String cardTypeName;	//卡类型名称
    private String hisUserId; ///医院用户ID
    private String icCardId; //就诊卡号
    private String callNo; //排队序号
    
	public String getCallNo() {
		return callNo;
	}

	public void setCallNo(String callNo) {
		this.callNo = callNo;
	}

	public String getIcCardId() {
		return icCardId;
	}

	public void setIcCardId(String icCardId) {
		this.icCardId = icCardId;
	}

	public String getHisUserId() {
		return hisUserId;
	}

	public void setHisUserId(String hisUserId) {
		this.hisUserId = hisUserId;
	}

	public BigDecimal getOrderMoney() {
		return orderMoney;
	}

	public void setOrderMoney(BigDecimal orderMoney) {
		this.orderMoney = orderMoney;
	}

	public String getOrderNo() {
		return orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	public String getCardNo() {
		return cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	public String getCardTypeName() {
		return cardTypeName;
	}

	public void setCardTypeName(String cardTypeName) {
		this.cardTypeName = cardTypeName;
	}

	public BigDecimal getOrderId() {
		return orderId;
	}

	public void setOrderId(BigDecimal orderId) {
		this.orderId = orderId;
	}

	public BigDecimal getFriendId() {
		return friendId;
	}

	public void setFriendId(BigDecimal friendId) {
		this.friendId = friendId;
	}

	public BigDecimal getAge() {
		return age;
	}

	public void setAge(BigDecimal age) {
		this.age = age;
	}

	public String getPickupAddr() {
		return pickupAddr;
	}

	public void setPickupAddr(String pickupAddr) {
		this.pickupAddr = pickupAddr;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.PERIOD_NAME
     *
     * @mbggenerated
     */
    private String periodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.STAFF_NAME
     *
     * @mbggenerated
     */
    private String staffName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.DEP_NAME
     *
     * @mbggenerated
     */
    private String depName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.ORG_NAME
     *
     * @mbggenerated
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.ID_CARD
     *
     * @mbggenerated
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.USER_BIRTH
     *
     * @mbggenerated
     */
    private String userBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.USER_SEX
     *
     * @mbggenerated
     */
    private String userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.USER_PHONE
     *
     * @mbggenerated
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.USER_ADDR
     *
     * @mbggenerated
     */
    private String userAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.REG_NUMBER
     *
     * @mbggenerated
     */
    private BigDecimal regNumber;
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.AMOUNT
     *
     * @mbggenerated
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.PAY_NUM
     *
     * @mbggenerated
     */
    private String payNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.STATUS
     *
     * @mbggenerated
     */
    //状态：0未付费1扣费成功2扣费中3扣费失败4退费成功5退费中6退费失败7免支付
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.IS_USED
     *
     * @mbggenerated
     */
    private String isUsed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.REG_UNIQUE_ID
     *
     * @mbggenerated
     */
    private String regUniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.CREATE_OPERATOR
     *
     * @mbggenerated
     */
    private BigDecimal createOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.CREATE_OPERATOR_NAME
     *
     * @mbggenerated
     */
    private String createOperatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.OPERATOR
     *
     * @mbggenerated
     */
    private BigDecimal operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.OPERATOR_NAME
     *
     * @mbggenerated
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.OP_TIME
     *
     * @mbggenerated
     */
    private Date opTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.PICKUP_TIME
     *
     * @mbggenerated
     */
    private Date pickupTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.PICKUP_OPERATOR
     *
     * @mbggenerated
     */
    private BigDecimal pickupOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.PICKUP_OPERATOR_NAME
     *
     * @mbggenerated
     */
    private String pickupOperatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.CANCEL_TIME
     *
     * @mbggenerated
     */
    private Date cancelTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.BACK_OPERATOR
     *
     * @mbggenerated
     */
    private BigDecimal backOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.BACK_OPERATOR_NAME
     *
     * @mbggenerated
     */
    private String backOperatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.BACK_OPERATOR_TYPE
     *
     * @mbggenerated
     */
    private BigDecimal backOperatorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.BACK_REASON
     *
     * @mbggenerated
     */
    private String backReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.QUITFEE_TIME
     *
     * @mbggenerated
     */
    private Date quitfeeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.QUITFEE_OPERATOR
     *
     * @mbggenerated
     */
    private BigDecimal quitfeeOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.QUITFEE_OPERATOR_NAME
     *
     * @mbggenerated
     */
    private String quitfeeOperatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.FIRSTVISITINDICCTOR
     *
     * @mbggenerated
     */
    private BigDecimal firstvisitindicctor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.DUTY_PERIOD_ID
     *
     * @mbggenerated
     */
    private BigDecimal dutyPeriodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.PERIOD_START_TIME
     *
     * @mbggenerated
     */
    private Date periodStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.PERIOD_END_TIME
     *
     * @mbggenerated
     */
    private Date periodEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.PERIOD_REG_TIME
     *
     * @mbggenerated
     */
    private String periodRegTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.PERIOD_UNIQUE_ID
     *
     * @mbggenerated
     */
    private String periodUniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.DSB
     *
     * @mbggenerated
     */
    private String dsb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.REG_WAY_ID
     *
     * @mbggenerated
     */
    private BigDecimal regWayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_REG.PAY_WAY_ID
     *
     * @mbggenerated
     */
    private BigDecimal payWayId;
    private BigDecimal userId;
    
    private BigDecimal staffTypeId;
	private String staffTypeName;
	
	private String staffIcon; //医生头像
	
	private String appointCode; //门诊挂号码
	
    public String getAppointCode() {
		return appointCode;
	}

	public void setAppointCode(String appointCode) {
		this.appointCode = appointCode;
	}

	public String getStaffIcon() {
		return staffIcon;
	}

	public void setStaffIcon(String staffIcon) {
		this.staffIcon = staffIcon;
	}

	public BigDecimal getStaffTypeId() {
		return staffTypeId;
	}

	public void setStaffTypeId(BigDecimal staffTypeId) {
		this.staffTypeId = staffTypeId;
	}

	public String getStaffTypeName() {
		return staffTypeName;
	}

	public void setStaffTypeName(String staffTypeName) {
		this.staffTypeName = staffTypeName;
	}
    public BigDecimal getUserId() {
		return userId;
	}

	public void setUserId(BigDecimal userId) {
		this.userId = userId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.REG_ID
     *
     * @return the value of MC_REG.REG_ID
     *
     * @mbggenerated
     */
    public BigDecimal getRegId() {
        return regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.REG_ID
     *
     * @param regId the value for MC_REG.REG_ID
     *
     * @mbggenerated
     */
    public void setRegId(BigDecimal regId) {
        this.regId = regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.ORG_ID
     *
     * @return the value of MC_REG.ORG_ID
     *
     * @mbggenerated
     */
    public BigDecimal getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.ORG_ID
     *
     * @param orgId the value for MC_REG.ORG_ID
     *
     * @mbggenerated
     */
    public void setOrgId(BigDecimal orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.DUTY_ID
     *
     * @return the value of MC_REG.DUTY_ID
     *
     * @mbggenerated
     */
    public BigDecimal getDutyId() {
        return dutyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.DUTY_ID
     *
     * @param dutyId the value for MC_REG.DUTY_ID
     *
     * @mbggenerated
     */
    public void setDutyId(BigDecimal dutyId) {
        this.dutyId = dutyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.DEP_ID
     *
     * @return the value of MC_REG.DEP_ID
     *
     * @mbggenerated
     */
    public BigDecimal getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.DEP_ID
     *
     * @param depId the value for MC_REG.DEP_ID
     *
     * @mbggenerated
     */
    public void setDepId(BigDecimal depId) {
        this.depId = depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.STAFF_ID
     *
     * @return the value of MC_REG.STAFF_ID
     *
     * @mbggenerated
     */
    public BigDecimal getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.STAFF_ID
     *
     * @param staffId the value for MC_REG.STAFF_ID
     *
     * @mbggenerated
     */
    public void setStaffId(BigDecimal staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.PERIOD_ID
     *
     * @return the value of MC_REG.PERIOD_ID
     *
     * @mbggenerated
     */
    public BigDecimal getPeriodId() {
        return periodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.PERIOD_ID
     *
     * @param periodId the value for MC_REG.PERIOD_ID
     *
     * @mbggenerated
     */
    public void setPeriodId(BigDecimal periodId) {
        this.periodId = periodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.REG_WAY_NAME
     *
     * @return the value of MC_REG.REG_WAY_NAME
     *
     * @mbggenerated
     */
    public String getRegWayName() {
        return regWayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.REG_WAY_NAME
     *
     * @param regWayName the value for MC_REG.REG_WAY_NAME
     *
     * @mbggenerated
     */
    public void setRegWayName(String regWayName) {
        this.regWayName = regWayName == null ? null : regWayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.PAY_WAY_NAME
     *
     * @return the value of MC_REG.PAY_WAY_NAME
     *
     * @mbggenerated
     */
    public String getPayWayName() {
        return payWayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.PAY_WAY_NAME
     *
     * @param payWayName the value for MC_REG.PAY_WAY_NAME
     *
     * @mbggenerated
     */
    public void setPayWayName(String payWayName) {
        this.payWayName = payWayName == null ? null : payWayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.ORDER_TIME
     *
     * @return the value of MC_REG.ORDER_TIME
     *
     * @mbggenerated
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.ORDER_TIME
     *
     * @param orderTime the value for MC_REG.ORDER_TIME
     *
     * @mbggenerated
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.PERIOD_NAME
     *
     * @return the value of MC_REG.PERIOD_NAME
     *
     * @mbggenerated
     */
    public String getPeriodName() {
        return periodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.PERIOD_NAME
     *
     * @param periodName the value for MC_REG.PERIOD_NAME
     *
     * @mbggenerated
     */
    public void setPeriodName(String periodName) {
        this.periodName = periodName == null ? null : periodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.STAFF_NAME
     *
     * @return the value of MC_REG.STAFF_NAME
     *
     * @mbggenerated
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.STAFF_NAME
     *
     * @param staffName the value for MC_REG.STAFF_NAME
     *
     * @mbggenerated
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.DEP_NAME
     *
     * @return the value of MC_REG.DEP_NAME
     *
     * @mbggenerated
     */
    public String getDepName() {
        return depName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.DEP_NAME
     *
     * @param depName the value for MC_REG.DEP_NAME
     *
     * @mbggenerated
     */
    public void setDepName(String depName) {
        this.depName = depName == null ? null : depName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.ORG_NAME
     *
     * @return the value of MC_REG.ORG_NAME
     *
     * @mbggenerated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.ORG_NAME
     *
     * @param orgName the value for MC_REG.ORG_NAME
     *
     * @mbggenerated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.USER_NAME
     *
     * @return the value of MC_REG.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.USER_NAME
     *
     * @param userName the value for MC_REG.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.ID_CARD
     *
     * @return the value of MC_REG.ID_CARD
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.ID_CARD
     *
     * @param idCard the value for MC_REG.ID_CARD
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.USER_BIRTH
     *
     * @return the value of MC_REG.USER_BIRTH
     *
     * @mbggenerated
     */
    public String getUserBirth() {
        return userBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.USER_BIRTH
     *
     * @param userBirth the value for MC_REG.USER_BIRTH
     *
     * @mbggenerated
     */
    public void setUserBirth(String userBirth) {
        this.userBirth = userBirth == null ? null : userBirth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.USER_SEX
     *
     * @return the value of MC_REG.USER_SEX
     *
     * @mbggenerated
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.USER_SEX
     *
     * @param userSex the value for MC_REG.USER_SEX
     *
     * @mbggenerated
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex == null ? null : userSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.USER_PHONE
     *
     * @return the value of MC_REG.USER_PHONE
     *
     * @mbggenerated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.USER_PHONE
     *
     * @param userPhone the value for MC_REG.USER_PHONE
     *
     * @mbggenerated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.USER_ADDR
     *
     * @return the value of MC_REG.USER_ADDR
     *
     * @mbggenerated
     */
    public String getUserAddr() {
        return userAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.USER_ADDR
     *
     * @param userAddr the value for MC_REG.USER_ADDR
     *
     * @mbggenerated
     */
    public void setUserAddr(String userAddr) {
        this.userAddr = userAddr == null ? null : userAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.REG_NUMBER
     *
     * @return the value of MC_REG.REG_NUMBER
     *
     * @mbggenerated
     */
    public BigDecimal getRegNumber() {
        return regNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.REG_NUMBER
     *
     * @param regNumber the value for MC_REG.REG_NUMBER
     *
     * @mbggenerated
     */
    public void setRegNumber(BigDecimal regNumber) {
        this.regNumber = regNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.AMOUNT
     *
     * @return the value of MC_REG.AMOUNT
     *
     * @mbggenerated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.AMOUNT
     *
     * @param amount the value for MC_REG.AMOUNT
     *
     * @mbggenerated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.PAY_NUM
     *
     * @return the value of MC_REG.PAY_NUM
     *
     * @mbggenerated
     */
    public String getPayNum() {
        return payNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.PAY_NUM
     *
     * @param payNum the value for MC_REG.PAY_NUM
     *
     * @mbggenerated
     */
    public void setPayNum(String payNum) {
        this.payNum = payNum == null ? null : payNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.STATUS
     *
     * @return the value of MC_REG.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.STATUS
     *
     * @param status the value for MC_REG.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.IS_USED
     *
     * @return the value of MC_REG.IS_USED
     *
     * @mbggenerated
     */
    public String getIsUsed() {
        return isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.IS_USED
     *
     * @param isUsed the value for MC_REG.IS_USED
     *
     * @mbggenerated
     */
    public void setIsUsed(String isUsed) {
        this.isUsed = isUsed == null ? null : isUsed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.REG_UNIQUE_ID
     *
     * @return the value of MC_REG.REG_UNIQUE_ID
     *
     * @mbggenerated
     */
    public String getRegUniqueId() {
        return regUniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.REG_UNIQUE_ID
     *
     * @param regUniqueId the value for MC_REG.REG_UNIQUE_ID
     *
     * @mbggenerated
     */
    public void setRegUniqueId(String regUniqueId) {
        this.regUniqueId = regUniqueId == null ? null : regUniqueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.CREATE_TIME
     *
     * @return the value of MC_REG.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.CREATE_TIME
     *
     * @param createTime the value for MC_REG.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.CREATE_OPERATOR
     *
     * @return the value of MC_REG.CREATE_OPERATOR
     *
     * @mbggenerated
     */
    public BigDecimal getCreateOperator() {
        return createOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.CREATE_OPERATOR
     *
     * @param createOperator the value for MC_REG.CREATE_OPERATOR
     *
     * @mbggenerated
     */
    public void setCreateOperator(BigDecimal createOperator) {
        this.createOperator = createOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.CREATE_OPERATOR_NAME
     *
     * @return the value of MC_REG.CREATE_OPERATOR_NAME
     *
     * @mbggenerated
     */
    public String getCreateOperatorName() {
        return createOperatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.CREATE_OPERATOR_NAME
     *
     * @param createOperatorName the value for MC_REG.CREATE_OPERATOR_NAME
     *
     * @mbggenerated
     */
    public void setCreateOperatorName(String createOperatorName) {
        this.createOperatorName = createOperatorName == null ? null : createOperatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.OPERATOR
     *
     * @return the value of MC_REG.OPERATOR
     *
     * @mbggenerated
     */
    public BigDecimal getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.OPERATOR
     *
     * @param operator the value for MC_REG.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(BigDecimal operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.OPERATOR_NAME
     *
     * @return the value of MC_REG.OPERATOR_NAME
     *
     * @mbggenerated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.OPERATOR_NAME
     *
     * @param operatorName the value for MC_REG.OPERATOR_NAME
     *
     * @mbggenerated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.OP_TIME
     *
     * @return the value of MC_REG.OP_TIME
     *
     * @mbggenerated
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.OP_TIME
     *
     * @param opTime the value for MC_REG.OP_TIME
     *
     * @mbggenerated
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.PICKUP_TIME
     *
     * @return the value of MC_REG.PICKUP_TIME
     *
     * @mbggenerated
     */
    public Date getPickupTime() {
        return pickupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.PICKUP_TIME
     *
     * @param pickupTime the value for MC_REG.PICKUP_TIME
     *
     * @mbggenerated
     */
    public void setPickupTime(Date pickupTime) {
        this.pickupTime = pickupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.PICKUP_OPERATOR
     *
     * @return the value of MC_REG.PICKUP_OPERATOR
     *
     * @mbggenerated
     */
    public BigDecimal getPickupOperator() {
        return pickupOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.PICKUP_OPERATOR
     *
     * @param pickupOperator the value for MC_REG.PICKUP_OPERATOR
     *
     * @mbggenerated
     */
    public void setPickupOperator(BigDecimal pickupOperator) {
        this.pickupOperator = pickupOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.PICKUP_OPERATOR_NAME
     *
     * @return the value of MC_REG.PICKUP_OPERATOR_NAME
     *
     * @mbggenerated
     */
    public String getPickupOperatorName() {
        return pickupOperatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.PICKUP_OPERATOR_NAME
     *
     * @param pickupOperatorName the value for MC_REG.PICKUP_OPERATOR_NAME
     *
     * @mbggenerated
     */
    public void setPickupOperatorName(String pickupOperatorName) {
        this.pickupOperatorName = pickupOperatorName == null ? null : pickupOperatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.CANCEL_TIME
     *
     * @return the value of MC_REG.CANCEL_TIME
     *
     * @mbggenerated
     */
    public Date getCancelTime() {
        return cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.CANCEL_TIME
     *
     * @param cancelTime the value for MC_REG.CANCEL_TIME
     *
     * @mbggenerated
     */
    public void setCancelTime(Date cancelTime) {
        this.cancelTime = cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.BACK_OPERATOR
     *
     * @return the value of MC_REG.BACK_OPERATOR
     *
     * @mbggenerated
     */
    public BigDecimal getBackOperator() {
        return backOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.BACK_OPERATOR
     *
     * @param backOperator the value for MC_REG.BACK_OPERATOR
     *
     * @mbggenerated
     */
    public void setBackOperator(BigDecimal backOperator) {
        this.backOperator = backOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.BACK_OPERATOR_NAME
     *
     * @return the value of MC_REG.BACK_OPERATOR_NAME
     *
     * @mbggenerated
     */
    public String getBackOperatorName() {
        return backOperatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.BACK_OPERATOR_NAME
     *
     * @param backOperatorName the value for MC_REG.BACK_OPERATOR_NAME
     *
     * @mbggenerated
     */
    public void setBackOperatorName(String backOperatorName) {
        this.backOperatorName = backOperatorName == null ? null : backOperatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.BACK_OPERATOR_TYPE
     *
     * @return the value of MC_REG.BACK_OPERATOR_TYPE
     *
     * @mbggenerated
     */
    public BigDecimal getBackOperatorType() {
        return backOperatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.BACK_OPERATOR_TYPE
     *
     * @param backOperatorType the value for MC_REG.BACK_OPERATOR_TYPE
     *
     * @mbggenerated
     */
    public void setBackOperatorType(BigDecimal backOperatorType) {
        this.backOperatorType = backOperatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.BACK_REASON
     *
     * @return the value of MC_REG.BACK_REASON
     *
     * @mbggenerated
     */
    public String getBackReason() {
        return backReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.BACK_REASON
     *
     * @param backReason the value for MC_REG.BACK_REASON
     *
     * @mbggenerated
     */
    public void setBackReason(String backReason) {
        this.backReason = backReason == null ? null : backReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.QUITFEE_TIME
     *
     * @return the value of MC_REG.QUITFEE_TIME
     *
     * @mbggenerated
     */
    public Date getQuitfeeTime() {
        return quitfeeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.QUITFEE_TIME
     *
     * @param quitfeeTime the value for MC_REG.QUITFEE_TIME
     *
     * @mbggenerated
     */
    public void setQuitfeeTime(Date quitfeeTime) {
        this.quitfeeTime = quitfeeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.QUITFEE_OPERATOR
     *
     * @return the value of MC_REG.QUITFEE_OPERATOR
     *
     * @mbggenerated
     */
    public BigDecimal getQuitfeeOperator() {
        return quitfeeOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.QUITFEE_OPERATOR
     *
     * @param quitfeeOperator the value for MC_REG.QUITFEE_OPERATOR
     *
     * @mbggenerated
     */
    public void setQuitfeeOperator(BigDecimal quitfeeOperator) {
        this.quitfeeOperator = quitfeeOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.QUITFEE_OPERATOR_NAME
     *
     * @return the value of MC_REG.QUITFEE_OPERATOR_NAME
     *
     * @mbggenerated
     */
    public String getQuitfeeOperatorName() {
        return quitfeeOperatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.QUITFEE_OPERATOR_NAME
     *
     * @param quitfeeOperatorName the value for MC_REG.QUITFEE_OPERATOR_NAME
     *
     * @mbggenerated
     */
    public void setQuitfeeOperatorName(String quitfeeOperatorName) {
        this.quitfeeOperatorName = quitfeeOperatorName == null ? null : quitfeeOperatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.REMARK
     *
     * @return the value of MC_REG.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.REMARK
     *
     * @param remark the value for MC_REG.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.FIRSTVISITINDICCTOR
     *
     * @return the value of MC_REG.FIRSTVISITINDICCTOR
     *
     * @mbggenerated
     */
    public BigDecimal getFirstvisitindicctor() {
        return firstvisitindicctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.FIRSTVISITINDICCTOR
     *
     * @param firstvisitindicctor the value for MC_REG.FIRSTVISITINDICCTOR
     *
     * @mbggenerated
     */
    public void setFirstvisitindicctor(BigDecimal firstvisitindicctor) {
        this.firstvisitindicctor = firstvisitindicctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.DUTY_PERIOD_ID
     *
     * @return the value of MC_REG.DUTY_PERIOD_ID
     *
     * @mbggenerated
     */
    public BigDecimal getDutyPeriodId() {
        return dutyPeriodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.DUTY_PERIOD_ID
     *
     * @param dutyPeriodId the value for MC_REG.DUTY_PERIOD_ID
     *
     * @mbggenerated
     */
    public void setDutyPeriodId(BigDecimal dutyPeriodId) {
        this.dutyPeriodId = dutyPeriodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.PERIOD_START_TIME
     *
     * @return the value of MC_REG.PERIOD_START_TIME
     *
     * @mbggenerated
     */
    public Date getPeriodStartTime() {
        return periodStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.PERIOD_START_TIME
     *
     * @param periodStartTime the value for MC_REG.PERIOD_START_TIME
     *
     * @mbggenerated
     */
    public void setPeriodStartTime(Date periodStartTime) {
        this.periodStartTime = periodStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.PERIOD_END_TIME
     *
     * @return the value of MC_REG.PERIOD_END_TIME
     *
     * @mbggenerated
     */
    public Date getPeriodEndTime() {
        return periodEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.PERIOD_END_TIME
     *
     * @param periodEndTime the value for MC_REG.PERIOD_END_TIME
     *
     * @mbggenerated
     */
    public void setPeriodEndTime(Date periodEndTime) {
        this.periodEndTime = periodEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.PERIOD_REG_TIME
     *
     * @return the value of MC_REG.PERIOD_REG_TIME
     *
     * @mbggenerated
     */
    public String getPeriodRegTime() {
        return periodRegTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.PERIOD_REG_TIME
     *
     * @param periodRegTime the value for MC_REG.PERIOD_REG_TIME
     *
     * @mbggenerated
     */
    public void setPeriodRegTime(String periodRegTime) {
        this.periodRegTime = periodRegTime == null ? null : periodRegTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.PERIOD_UNIQUE_ID
     *
     * @return the value of MC_REG.PERIOD_UNIQUE_ID
     *
     * @mbggenerated
     */
    public String getPeriodUniqueId() {
        return periodUniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.PERIOD_UNIQUE_ID
     *
     * @param periodUniqueId the value for MC_REG.PERIOD_UNIQUE_ID
     *
     * @mbggenerated
     */
    public void setPeriodUniqueId(String periodUniqueId) {
        this.periodUniqueId = periodUniqueId == null ? null : periodUniqueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.DSB
     *
     * @return the value of MC_REG.DSB
     *
     * @mbggenerated
     */
    public String getDsb() {
        return dsb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.DSB
     *
     * @param dsb the value for MC_REG.DSB
     *
     * @mbggenerated
     */
    public void setDsb(String dsb) {
        this.dsb = dsb == null ? null : dsb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.REG_WAY_ID
     *
     * @return the value of MC_REG.REG_WAY_ID
     *
     * @mbggenerated
     */
    public BigDecimal getRegWayId() {
        return regWayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.REG_WAY_ID
     *
     * @param regWayId the value for MC_REG.REG_WAY_ID
     *
     * @mbggenerated
     */
    public void setRegWayId(BigDecimal regWayId) {
        this.regWayId = regWayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_REG.PAY_WAY_ID
     *
     * @return the value of MC_REG.PAY_WAY_ID
     *
     * @mbggenerated
     */
    public BigDecimal getPayWayId() {
        return payWayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_REG.PAY_WAY_ID
     *
     * @param payWayId the value for MC_REG.PAY_WAY_ID
     *
     * @mbggenerated
     */
    public void setPayWayId(BigDecimal payWayId) {
        this.payWayId = payWayId;
    }

    private Integer isBund = 0;// 0不绑定 1 绑定
    
    public void setIsBund(Integer isBund) {
		this.isBund = isBund;
	}
	public Integer getIsBund() {
		return isBund;
	}
}