package com.unique.reg.po;

import java.math.BigDecimal;
import java.util.Date;

public class PayWay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAY.PAY_WAY_ID
     *
     * @mbggenerated
     */
    private BigDecimal payWayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAY.PAY_WAY_CODE
     *
     * @mbggenerated
     */
    private String payWayCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAY.REG_WAY_NAME
     *
     * @mbggenerated
     */
    private String payWayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAY.SORT_RANK
     *
     * @mbggenerated
     */
    private BigDecimal sortRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAY.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAY.OPERATOR
     *
     * @mbggenerated
     */
    private BigDecimal operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAY.OP_TIME
     *
     * @mbggenerated
     */
    private Date opTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAY.OPERATOR_NAME
     *
     * @mbggenerated
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAY.POUNDAGE
     *
     * @mbggenerated
     */
    private BigDecimal poundage;
    private String config;
    
    private String refund;
    
    public String getConfig() {
		return config;
	}

	public void setConfig(String config) {
		this.config = config;
	}

	public String getRefund() {
		return refund;
	}

	public void setRefund(String refund) {
		this.refund = refund;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAY.PAY_WAY_ID
     *
     * @return the value of PAY_WAY.PAY_WAY_ID
     *
     * @mbggenerated
     */
    public BigDecimal getPayWayId() {
        return payWayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAY.PAY_WAY_ID
     *
     * @param payWayId the value for PAY_WAY.PAY_WAY_ID
     *
     * @mbggenerated
     */
    public void setPayWayId(BigDecimal payWayId) {
        this.payWayId = payWayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAY.PAY_WAY_CODE
     *
     * @return the value of PAY_WAY.PAY_WAY_CODE
     *
     * @mbggenerated
     */
    public String getPayWayCode() {
        return payWayCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAY.PAY_WAY_CODE
     *
     * @param payWayCode the value for PAY_WAY.PAY_WAY_CODE
     *
     * @mbggenerated
     */
    public void setPayWayCode(String payWayCode) {
        this.payWayCode = payWayCode == null ? null : payWayCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAY.REG_WAY_NAME
     *
     * @return the value of PAY_WAY.REG_WAY_NAME
     *
     * @mbggenerated
     */
    public String getPayWayName() {
        return payWayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAY.REG_WAY_NAME
     *
     * @param regWayName the value for PAY_WAY.REG_WAY_NAME
     *
     * @mbggenerated
     */
    public void setPayWayName(String payWayName) {
        this.payWayName = payWayName == null ? null : payWayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAY.SORT_RANK
     *
     * @return the value of PAY_WAY.SORT_RANK
     *
     * @mbggenerated
     */
    public BigDecimal getSortRank() {
        return sortRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAY.SORT_RANK
     *
     * @param sortRank the value for PAY_WAY.SORT_RANK
     *
     * @mbggenerated
     */
    public void setSortRank(BigDecimal sortRank) {
        this.sortRank = sortRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAY.STATUS
     *
     * @return the value of PAY_WAY.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAY.STATUS
     *
     * @param status the value for PAY_WAY.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAY.OPERATOR
     *
     * @return the value of PAY_WAY.OPERATOR
     *
     * @mbggenerated
     */
    public BigDecimal getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAY.OPERATOR
     *
     * @param operator the value for PAY_WAY.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(BigDecimal operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAY.OP_TIME
     *
     * @return the value of PAY_WAY.OP_TIME
     *
     * @mbggenerated
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAY.OP_TIME
     *
     * @param opTime the value for PAY_WAY.OP_TIME
     *
     * @mbggenerated
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAY.OPERATOR_NAME
     *
     * @return the value of PAY_WAY.OPERATOR_NAME
     *
     * @mbggenerated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAY.OPERATOR_NAME
     *
     * @param operatorName the value for PAY_WAY.OPERATOR_NAME
     *
     * @mbggenerated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAY.POUNDAGE
     *
     * @return the value of PAY_WAY.POUNDAGE
     *
     * @mbggenerated
     */
    public BigDecimal getPoundage() {
        return poundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAY.POUNDAGE
     *
     * @param poundage the value for PAY_WAY.POUNDAGE
     *
     * @mbggenerated
     */
    public void setPoundage(BigDecimal poundage) {
        this.poundage = poundage;
    }
}