package com.unique.reg.po;

import java.math.BigDecimal;
import java.util.Date;

public class ProductPriceType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_PRICE_TYPE.TYPE_ID
     *
     * @mbggenerated
     */
    private BigDecimal typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_PRICE_TYPE.TYPE_CODE
     *
     * @mbggenerated
     */
    private String typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_PRICE_TYPE.TYPE_NAME
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_PRICE_TYPE.IS_SYSTEM
     *
     * @mbggenerated
     */
    private String isSystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_PRICE_TYPE.OPERATOR
     *
     * @mbggenerated
     */
    private BigDecimal operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_PRICE_TYPE.OP_TIME
     *
     * @mbggenerated
     */
    private Date opTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_PRICE_TYPE.OPERATOR_NAME
     *
     * @mbggenerated
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_PRICE_TYPE.ORG_ID
     *
     * @mbggenerated
     */
    private BigDecimal orgId;

    private BigDecimal price;
    
    public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_PRICE_TYPE.TYPE_ID
     *
     * @return the value of PRODUCT_PRICE_TYPE.TYPE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_PRICE_TYPE.TYPE_ID
     *
     * @param typeId the value for PRODUCT_PRICE_TYPE.TYPE_ID
     *
     * @mbggenerated
     */
    public void setTypeId(BigDecimal typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_PRICE_TYPE.TYPE_CODE
     *
     * @return the value of PRODUCT_PRICE_TYPE.TYPE_CODE
     *
     * @mbggenerated
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_PRICE_TYPE.TYPE_CODE
     *
     * @param typeCode the value for PRODUCT_PRICE_TYPE.TYPE_CODE
     *
     * @mbggenerated
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_PRICE_TYPE.TYPE_NAME
     *
     * @return the value of PRODUCT_PRICE_TYPE.TYPE_NAME
     *
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_PRICE_TYPE.TYPE_NAME
     *
     * @param typeName the value for PRODUCT_PRICE_TYPE.TYPE_NAME
     *
     * @mbggenerated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_PRICE_TYPE.IS_SYSTEM
     *
     * @return the value of PRODUCT_PRICE_TYPE.IS_SYSTEM
     *
     * @mbggenerated
     */
    public String getIsSystem() {
        return isSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_PRICE_TYPE.IS_SYSTEM
     *
     * @param isSystem the value for PRODUCT_PRICE_TYPE.IS_SYSTEM
     *
     * @mbggenerated
     */
    public void setIsSystem(String isSystem) {
        this.isSystem = isSystem == null ? null : isSystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_PRICE_TYPE.OPERATOR
     *
     * @return the value of PRODUCT_PRICE_TYPE.OPERATOR
     *
     * @mbggenerated
     */
    public BigDecimal getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_PRICE_TYPE.OPERATOR
     *
     * @param operator the value for PRODUCT_PRICE_TYPE.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(BigDecimal operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_PRICE_TYPE.OP_TIME
     *
     * @return the value of PRODUCT_PRICE_TYPE.OP_TIME
     *
     * @mbggenerated
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_PRICE_TYPE.OP_TIME
     *
     * @param opTime the value for PRODUCT_PRICE_TYPE.OP_TIME
     *
     * @mbggenerated
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_PRICE_TYPE.OPERATOR_NAME
     *
     * @return the value of PRODUCT_PRICE_TYPE.OPERATOR_NAME
     *
     * @mbggenerated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_PRICE_TYPE.OPERATOR_NAME
     *
     * @param operatorName the value for PRODUCT_PRICE_TYPE.OPERATOR_NAME
     *
     * @mbggenerated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_PRICE_TYPE.ORG_ID
     *
     * @return the value of PRODUCT_PRICE_TYPE.ORG_ID
     *
     * @mbggenerated
     */
    public BigDecimal getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_PRICE_TYPE.ORG_ID
     *
     * @param orgId the value for PRODUCT_PRICE_TYPE.ORG_ID
     *
     * @mbggenerated
     */
    public void setOrgId(BigDecimal orgId) {
        this.orgId = orgId;
    }
}