package com.unique.system.po;

import java.math.BigDecimal;
import java.util.Date;

public class ImMsgInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_MSG_INFO.IM_ID
     *
     * @mbggenerated
     */
    private BigDecimal imId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_MSG_INFO.CONTENT_TYPE
     *
     * @mbggenerated
     */
    private String contentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_MSG_INFO.FROM_USER
     *
     * @mbggenerated
     */
    private BigDecimal fromUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_MSG_INFO.TO_USER
     *
     * @mbggenerated
     */
    private BigDecimal toUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_MSG_INFO.URL
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_MSG_INFO.STATS
     *
     * @mbggenerated
     */
    private String stats;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_MSG_INFO.SEND_TIME
     *
     * @mbggenerated
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IM_MSG_INFO.CONTENT
     *
     * @mbggenerated
     */
    private String content;
    private String msgOrtherCon;
    
    public String getUserUserName() {
		return userUserName;
	}

	public void setUserUserName(String userUserName) {
		this.userUserName = userUserName;
	}

	public String getStaffUserName() {
		return staffUserName;
	}

	public void setStaffUserName(String staffUserName) {
		this.staffUserName = staffUserName;
	}

	private String userUserName;
    private String staffUserName;
    
    
    public String getMsgOrtherCon() {
		return msgOrtherCon;
	}

	public void setMsgOrtherCon(String msgOrtherCon) {
		this.msgOrtherCon = msgOrtherCon;
	}

	private BigDecimal relationUserId;	
    private BigDecimal relationStaffId;

    public BigDecimal getRelationUserId() {
		return relationUserId;
	}

	public void setRelationUserId(BigDecimal relationUserId) {
		this.relationUserId = relationUserId;
	}

	public BigDecimal getRelationStaffId() {
		return relationStaffId;
	}

	public void setRelationStaffId(BigDecimal relationStaffId) {
		this.relationStaffId = relationStaffId;
	}

	public String getFromUserName() {
		return fromUserName;
	}

	public void setFromUserName(String fromUserName) {
		this.fromUserName = fromUserName;
	}

	public String getToUserName() {
		return toUserName;
	}

	public void setToUserName(String toUserName) {
		this.toUserName = toUserName;
	}

	private String fromUserName;
    private String toUserName;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_MSG_INFO.IM_ID
     *
     * @return the value of IM_MSG_INFO.IM_ID
     *
     * @mbggenerated
     */
    public BigDecimal getImId() {
        return imId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_MSG_INFO.IM_ID
     *
     * @param imId the value for IM_MSG_INFO.IM_ID
     *
     * @mbggenerated
     */
    public void setImId(BigDecimal imId) {
        this.imId = imId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_MSG_INFO.CONTENT_TYPE
     *
     * @return the value of IM_MSG_INFO.CONTENT_TYPE
     *
     * @mbggenerated
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_MSG_INFO.CONTENT_TYPE
     *
     * @param contentType the value for IM_MSG_INFO.CONTENT_TYPE
     *
     * @mbggenerated
     */
    public void setContentType(String contentType) {
        this.contentType = contentType == null ? null : contentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_MSG_INFO.FROM_USER
     *
     * @return the value of IM_MSG_INFO.FROM_USER
     *
     * @mbggenerated
     */
    public BigDecimal getFromUser() {
        return fromUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_MSG_INFO.FROM_USER
     *
     * @param fromUser the value for IM_MSG_INFO.FROM_USER
     *
     * @mbggenerated
     */
    public void setFromUser(BigDecimal fromUser) {
        this.fromUser = fromUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_MSG_INFO.TO_USER
     *
     * @return the value of IM_MSG_INFO.TO_USER
     *
     * @mbggenerated
     */
    public BigDecimal getToUser() {
        return toUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_MSG_INFO.TO_USER
     *
     * @param toUser the value for IM_MSG_INFO.TO_USER
     *
     * @mbggenerated
     */
    public void setToUser(BigDecimal toUser) {
        this.toUser = toUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_MSG_INFO.URL
     *
     * @return the value of IM_MSG_INFO.URL
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_MSG_INFO.URL
     *
     * @param url the value for IM_MSG_INFO.URL
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_MSG_INFO.STATS
     *
     * @return the value of IM_MSG_INFO.STATS
     *
     * @mbggenerated
     */
    public String getStats() {
        return stats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_MSG_INFO.STATS
     *
     * @param stats the value for IM_MSG_INFO.STATS
     *
     * @mbggenerated
     */
    public void setStats(String stats) {
        this.stats = stats == null ? null : stats.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_MSG_INFO.SEND_TIME
     *
     * @return the value of IM_MSG_INFO.SEND_TIME
     *
     * @mbggenerated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_MSG_INFO.SEND_TIME
     *
     * @param sendTime the value for IM_MSG_INFO.SEND_TIME
     *
     * @mbggenerated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IM_MSG_INFO.CONTENT
     *
     * @return the value of IM_MSG_INFO.CONTENT
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IM_MSG_INFO.CONTENT
     *
     * @param content the value for IM_MSG_INFO.CONTENT
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}