package com.unique.system.po;

import java.math.BigDecimal;
import java.util.Date;

public class VersionConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VERSION_CONFIG.VER_ID
     *
     * @mbggenerated
     */
    private BigDecimal verId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VERSION_CONFIG.VER_TYPE
     *
     * @mbggenerated
     */
    private String verType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VERSION_CONFIG.VER_VALUE
     *
     * @mbggenerated
     */
    private String verValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VERSION_CONFIG.VER_UPDATE
     *
     * @mbggenerated
     */
    private String verUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VERSION_CONFIG.VER_CON
     *
     * @mbggenerated
     */
    private String verCon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VERSION_CONFIG.VER_ADDR
     *
     * @mbggenerated
     */
    private String verAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VERSION_CONFIG.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VERSION_CONFIG.CLIENT_TYPE_ID
     *
     * @mbggenerated
     */
    private Integer clientTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VERSION_CONFIG.CLIENT_TYPE_NAME
     *
     * @mbggenerated
     */
    private String clientTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VERSION_CONFIG.PUBLISH_TIME
     *
     * @mbggenerated
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VERSION_CONFIG.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VERSION_CONFIG.UPGRADE_VERSION
     *
     * @mbggenerated
     */
    private String upgradeVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VERSION_CONFIG.DEL_STATUS
     *
     * @mbggenerated
     */
    private String delStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VERSION_CONFIG.VER_ID
     *
     * @return the value of VERSION_CONFIG.VER_ID
     *
     * @mbggenerated
     */
    public BigDecimal getVerId() {
        return verId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VERSION_CONFIG.VER_ID
     *
     * @param verId the value for VERSION_CONFIG.VER_ID
     *
     * @mbggenerated
     */
    public void setVerId(BigDecimal verId) {
        this.verId = verId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VERSION_CONFIG.VER_TYPE
     *
     * @return the value of VERSION_CONFIG.VER_TYPE
     *
     * @mbggenerated
     */
    public String getVerType() {
        return verType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VERSION_CONFIG.VER_TYPE
     *
     * @param verType the value for VERSION_CONFIG.VER_TYPE
     *
     * @mbggenerated
     */
    public void setVerType(String verType) {
        this.verType = verType == null ? null : verType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VERSION_CONFIG.VER_VALUE
     *
     * @return the value of VERSION_CONFIG.VER_VALUE
     *
     * @mbggenerated
     */
    public String getVerValue() {
        return verValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VERSION_CONFIG.VER_VALUE
     *
     * @param verValue the value for VERSION_CONFIG.VER_VALUE
     *
     * @mbggenerated
     */
    public void setVerValue(String verValue) {
        this.verValue = verValue == null ? null : verValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VERSION_CONFIG.VER_UPDATE
     *
     * @return the value of VERSION_CONFIG.VER_UPDATE
     *
     * @mbggenerated
     */
    public String getVerUpdate() {
        return verUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VERSION_CONFIG.VER_UPDATE
     *
     * @param verUpdate the value for VERSION_CONFIG.VER_UPDATE
     *
     * @mbggenerated
     */
    public void setVerUpdate(String verUpdate) {
        this.verUpdate = verUpdate == null ? null : verUpdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VERSION_CONFIG.VER_CON
     *
     * @return the value of VERSION_CONFIG.VER_CON
     *
     * @mbggenerated
     */
    public String getVerCon() {
        return verCon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VERSION_CONFIG.VER_CON
     *
     * @param verCon the value for VERSION_CONFIG.VER_CON
     *
     * @mbggenerated
     */
    public void setVerCon(String verCon) {
        this.verCon = verCon == null ? null : verCon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VERSION_CONFIG.VER_ADDR
     *
     * @return the value of VERSION_CONFIG.VER_ADDR
     *
     * @mbggenerated
     */
    public String getVerAddr() {
        return verAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VERSION_CONFIG.VER_ADDR
     *
     * @param verAddr the value for VERSION_CONFIG.VER_ADDR
     *
     * @mbggenerated
     */
    public void setVerAddr(String verAddr) {
        this.verAddr = verAddr == null ? null : verAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VERSION_CONFIG.REMARK
     *
     * @return the value of VERSION_CONFIG.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VERSION_CONFIG.REMARK
     *
     * @param remark the value for VERSION_CONFIG.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VERSION_CONFIG.CLIENT_TYPE_ID
     *
     * @return the value of VERSION_CONFIG.CLIENT_TYPE_ID
     *
     * @mbggenerated
     */
    public Integer getClientTypeId() {
        return clientTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VERSION_CONFIG.CLIENT_TYPE_ID
     *
     * @param clientTypeId the value for VERSION_CONFIG.CLIENT_TYPE_ID
     *
     * @mbggenerated
     */
    public void setClientTypeId(Integer clientTypeId) {
        this.clientTypeId = clientTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VERSION_CONFIG.CLIENT_TYPE_NAME
     *
     * @return the value of VERSION_CONFIG.CLIENT_TYPE_NAME
     *
     * @mbggenerated
     */
    public String getClientTypeName() {
        return clientTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VERSION_CONFIG.CLIENT_TYPE_NAME
     *
     * @param clientTypeName the value for VERSION_CONFIG.CLIENT_TYPE_NAME
     *
     * @mbggenerated
     */
    public void setClientTypeName(String clientTypeName) {
        this.clientTypeName = clientTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VERSION_CONFIG.PUBLISH_TIME
     *
     * @return the value of VERSION_CONFIG.PUBLISH_TIME
     *
     * @mbggenerated
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VERSION_CONFIG.PUBLISH_TIME
     *
     * @param publishTime the value for VERSION_CONFIG.PUBLISH_TIME
     *
     * @mbggenerated
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VERSION_CONFIG.STATUS
     *
     * @return the value of VERSION_CONFIG.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VERSION_CONFIG.STATUS
     *
     * @param status the value for VERSION_CONFIG.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VERSION_CONFIG.UPGRADE_VERSION
     *
     * @return the value of VERSION_CONFIG.UPGRADE_VERSION
     *
     * @mbggenerated
     */
    public String getUpgradeVersion() {
        return upgradeVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VERSION_CONFIG.UPGRADE_VERSION
     *
     * @param upgradeVersion the value for VERSION_CONFIG.UPGRADE_VERSION
     *
     * @mbggenerated
     */
    public void setUpgradeVersion(String upgradeVersion) {
        this.upgradeVersion = upgradeVersion == null ? null : upgradeVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VERSION_CONFIG.DEL_STATUS
     *
     * @return the value of VERSION_CONFIG.DEL_STATUS
     *
     * @mbggenerated
     */
    public String getDelStatus() {
        return delStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VERSION_CONFIG.DEL_STATUS
     *
     * @param delStatus the value for VERSION_CONFIG.DEL_STATUS
     *
     * @mbggenerated
     */
    public void setDelStatus(String delStatus) {
        this.delStatus = delStatus == null ? null : delStatus.trim();
    }
}