package com.unique.guide.po;

import java.math.BigDecimal;
import java.util.Date;

public class JbIllness {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.ILL_ID
     *
     * @mbggenerated
     */
    private BigDecimal illId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.ILL_NAME
     *
     * @mbggenerated
     */
    private String illName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.ILL_CODE
     *
     * @mbggenerated
     */
    private String illCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.ILL_ALIAS
     *
     * @mbggenerated
     */
    private String illAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.ILL_EN_NAME
     *
     * @mbggenerated
     */
    private String illEnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.ILL_OFTEN_PATHOGENY
     *
     * @mbggenerated
     */
    private String illOftenPathogeny;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.ILL_OFTEN_SYMPTOMS
     *
     * @mbggenerated
     */
    private String illOftenSymptoms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.ILL_IMG
     *
     * @mbggenerated
     */
    private String illImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.ILL_INCIDENCE
     *
     * @mbggenerated
     */
    private String illIncidence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.ILL_INFECTIVITY
     *
     * @mbggenerated
     */
    private String illInfectivity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.ILL_MEDICAL_INSURANCE
     *
     * @mbggenerated
     */
    private String illMedicalInsurance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.OPERATOR_NAME
     *
     * @mbggenerated
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.OPERATOR
     *
     * @mbggenerated
     */
    private BigDecimal operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.OP_TIME
     *
     * @mbggenerated
     */
    private Date opTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.ILL_DEP
     *
     * @mbggenerated
     */
    private String illDep;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.ILL_TXT
     *
     * @mbggenerated
     */
    private String illTxt;

    private String illLike; //相识度
    
    private int isShow; // 状态IllText 为null时，不予显示 0 不显示 1显示
    
    public int getIsShow() {
		return isShow;
	}

	public void setIsShow(int isShow) {
		this.isShow = isShow;
	}

	public String getIllLike() {
		return illLike;
	}

	public void setIllLike(String illLike) {
		this.illLike = illLike;
	}

	public String getIllTxt() {
		return illTxt;
	}

	public void setIllTxt(String illTxt) {
		this.illTxt = illTxt;
	}

	public String getIllFoodTherapyTxt() {
		return illFoodTherapyTxt;
	}

	public void setIllFoodTherapyTxt(String illFoodTherapyTxt) {
		this.illFoodTherapyTxt = illFoodTherapyTxt;
	}

	public String getIllPathogenyTxt() {
		return illPathogenyTxt;
	}

	public void setIllPathogenyTxt(String illPathogenyTxt) {
		this.illPathogenyTxt = illPathogenyTxt;
	}

	public String getIllCheckTxt() {
		return illCheckTxt;
	}

	public void setIllCheckTxt(String illCheckTxt) {
		this.illCheckTxt = illCheckTxt;
	}

	public String getIllConcurrentTxt() {
		return illConcurrentTxt;
	}

	public void setIllConcurrentTxt(String illConcurrentTxt) {
		this.illConcurrentTxt = illConcurrentTxt;
	}

	public String getIllPremunitionTxt() {
		return illPremunitionTxt;
	}

	public void setIllPremunitionTxt(String illPremunitionTxt) {
		this.illPremunitionTxt = illPremunitionTxt;
	}

	public String getIllNursingTxt() {
		return illNursingTxt;
	}

	public void setIllNursingTxt(String illNursingTxt) {
		this.illNursingTxt = illNursingTxt;
	}

	public String getIllSymptomsTxt() {
		return illSymptomsTxt;
	}

	public void setIllSymptomsTxt(String illSymptomsTxt) {
		this.illSymptomsTxt = illSymptomsTxt;
	}

	public String getIllDiagnosis() {
		return illDiagnosis;
	}

	public void setIllDiagnosis(String illDiagnosis) {
		this.illDiagnosis = illDiagnosis;
	}

	public String getIllPrognosis() {
		return illPrognosis;
	}

	public void setIllPrognosis(String illPrognosis) {
		this.illPrognosis = illPrognosis;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.ILL_FOOD_THERAPY_TXT
     *
     * @mbggenerated
     */
    private String illFoodTherapyTxt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.ILL_PATHOGENY_TXT
     *
     * @mbggenerated
     */
    private String illPathogenyTxt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.ILL_CHECK_TXT
     *
     * @mbggenerated
     */
    private String illCheckTxt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.ILL_CONCURRENT_TXT
     *
     * @mbggenerated
     */
    private String illConcurrentTxt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.ILL_PREMUNITION_TXT
     *
     * @mbggenerated
     */
    private String illPremunitionTxt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.ILL_NURSING_TXT
     *
     * @mbggenerated
     */
    private String illNursingTxt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.ILL_SYMPTOMS_TXT
     *
     * @mbggenerated
     */
    private String illSymptomsTxt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.ILL_DIAGNOSIS
     *
     * @mbggenerated
     */
    private String illDiagnosis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JB_ILLNESS.ILL_PROGNOSIS
     *
     * @mbggenerated
     */
    private String illPrognosis;
    
    private String illClassify;
    public String getIllClassify() {
		return illClassify;
	}

	public void setIllClassify(String illClassify) {
		this.illClassify = illClassify;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JB_ILLNESS.ILL_ID
     *
     * @return the value of JB_ILLNESS.ILL_ID
     *
     * @mbggenerated
     */
    public BigDecimal getIllId() {
        return illId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JB_ILLNESS.ILL_ID
     *
     * @param illId the value for JB_ILLNESS.ILL_ID
     *
     * @mbggenerated
     */
    public void setIllId(BigDecimal illId) {
        this.illId = illId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JB_ILLNESS.ILL_NAME
     *
     * @return the value of JB_ILLNESS.ILL_NAME
     *
     * @mbggenerated
     */
    public String getIllName() {
        return illName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JB_ILLNESS.ILL_NAME
     *
     * @param illName the value for JB_ILLNESS.ILL_NAME
     *
     * @mbggenerated
     */
    public void setIllName(String illName) {
        this.illName = illName == null ? null : illName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JB_ILLNESS.ILL_CODE
     *
     * @return the value of JB_ILLNESS.ILL_CODE
     *
     * @mbggenerated
     */
    public String getIllCode() {
        return illCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JB_ILLNESS.ILL_CODE
     *
     * @param illCode the value for JB_ILLNESS.ILL_CODE
     *
     * @mbggenerated
     */
    public void setIllCode(String illCode) {
        this.illCode = illCode == null ? null : illCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JB_ILLNESS.ILL_ALIAS
     *
     * @return the value of JB_ILLNESS.ILL_ALIAS
     *
     * @mbggenerated
     */
    public String getIllAlias() {
        return illAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JB_ILLNESS.ILL_ALIAS
     *
     * @param illAlias the value for JB_ILLNESS.ILL_ALIAS
     *
     * @mbggenerated
     */
    public void setIllAlias(String illAlias) {
        this.illAlias = illAlias == null ? null : illAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JB_ILLNESS.ILL_EN_NAME
     *
     * @return the value of JB_ILLNESS.ILL_EN_NAME
     *
     * @mbggenerated
     */
    public String getIllEnName() {
        return illEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JB_ILLNESS.ILL_EN_NAME
     *
     * @param illEnName the value for JB_ILLNESS.ILL_EN_NAME
     *
     * @mbggenerated
     */
    public void setIllEnName(String illEnName) {
        this.illEnName = illEnName == null ? null : illEnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JB_ILLNESS.ILL_OFTEN_PATHOGENY
     *
     * @return the value of JB_ILLNESS.ILL_OFTEN_PATHOGENY
     *
     * @mbggenerated
     */
    public String getIllOftenPathogeny() {
        return illOftenPathogeny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JB_ILLNESS.ILL_OFTEN_PATHOGENY
     *
     * @param illOftenPathogeny the value for JB_ILLNESS.ILL_OFTEN_PATHOGENY
     *
     * @mbggenerated
     */
    public void setIllOftenPathogeny(String illOftenPathogeny) {
        this.illOftenPathogeny = illOftenPathogeny == null ? null : illOftenPathogeny.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JB_ILLNESS.ILL_OFTEN_SYMPTOMS
     *
     * @return the value of JB_ILLNESS.ILL_OFTEN_SYMPTOMS
     *
     * @mbggenerated
     */
    public String getIllOftenSymptoms() {
        return illOftenSymptoms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JB_ILLNESS.ILL_OFTEN_SYMPTOMS
     *
     * @param illOftenSymptoms the value for JB_ILLNESS.ILL_OFTEN_SYMPTOMS
     *
     * @mbggenerated
     */
    public void setIllOftenSymptoms(String illOftenSymptoms) {
        this.illOftenSymptoms = illOftenSymptoms == null ? null : illOftenSymptoms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JB_ILLNESS.ILL_IMG
     *
     * @return the value of JB_ILLNESS.ILL_IMG
     *
     * @mbggenerated
     */
    public String getIllImg() {
        return illImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JB_ILLNESS.ILL_IMG
     *
     * @param illImg the value for JB_ILLNESS.ILL_IMG
     *
     * @mbggenerated
     */
    public void setIllImg(String illImg) {
        this.illImg = illImg == null ? null : illImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JB_ILLNESS.ILL_INCIDENCE
     *
     * @return the value of JB_ILLNESS.ILL_INCIDENCE
     *
     * @mbggenerated
     */
    public String getIllIncidence() {
        return illIncidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JB_ILLNESS.ILL_INCIDENCE
     *
     * @param illIncidence the value for JB_ILLNESS.ILL_INCIDENCE
     *
     * @mbggenerated
     */
    public void setIllIncidence(String illIncidence) {
        this.illIncidence = illIncidence == null ? null : illIncidence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JB_ILLNESS.ILL_INFECTIVITY
     *
     * @return the value of JB_ILLNESS.ILL_INFECTIVITY
     *
     * @mbggenerated
     */
    public String getIllInfectivity() {
        return illInfectivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JB_ILLNESS.ILL_INFECTIVITY
     *
     * @param illInfectivity the value for JB_ILLNESS.ILL_INFECTIVITY
     *
     * @mbggenerated
     */
    public void setIllInfectivity(String illInfectivity) {
        this.illInfectivity = illInfectivity == null ? null : illInfectivity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JB_ILLNESS.ILL_MEDICAL_INSURANCE
     *
     * @return the value of JB_ILLNESS.ILL_MEDICAL_INSURANCE
     *
     * @mbggenerated
     */
    public String getIllMedicalInsurance() {
        return illMedicalInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JB_ILLNESS.ILL_MEDICAL_INSURANCE
     *
     * @param illMedicalInsurance the value for JB_ILLNESS.ILL_MEDICAL_INSURANCE
     *
     * @mbggenerated
     */
    public void setIllMedicalInsurance(String illMedicalInsurance) {
        this.illMedicalInsurance = illMedicalInsurance == null ? null : illMedicalInsurance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JB_ILLNESS.STATUS
     *
     * @return the value of JB_ILLNESS.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JB_ILLNESS.STATUS
     *
     * @param status the value for JB_ILLNESS.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JB_ILLNESS.OPERATOR_NAME
     *
     * @return the value of JB_ILLNESS.OPERATOR_NAME
     *
     * @mbggenerated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JB_ILLNESS.OPERATOR_NAME
     *
     * @param operatorName the value for JB_ILLNESS.OPERATOR_NAME
     *
     * @mbggenerated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JB_ILLNESS.OPERATOR
     *
     * @return the value of JB_ILLNESS.OPERATOR
     *
     * @mbggenerated
     */
    public BigDecimal getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JB_ILLNESS.OPERATOR
     *
     * @param operator the value for JB_ILLNESS.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(BigDecimal operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JB_ILLNESS.OP_TIME
     *
     * @return the value of JB_ILLNESS.OP_TIME
     *
     * @mbggenerated
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JB_ILLNESS.OP_TIME
     *
     * @param opTime the value for JB_ILLNESS.OP_TIME
     *
     * @mbggenerated
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JB_ILLNESS.ILL_DEP
     *
     * @return the value of JB_ILLNESS.ILL_DEP
     *
     * @mbggenerated
     */
    public String getIllDep() {
        return illDep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JB_ILLNESS.ILL_DEP
     *
     * @param illDep the value for JB_ILLNESS.ILL_DEP
     *
     * @mbggenerated
     */
    public void setIllDep(String illDep) {
        this.illDep = illDep == null ? null : illDep.trim();
    }
}