package com.unique.survey.po;

import java.math.BigDecimal;
import java.util.Date;

public class ScoreRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCORE_RULE.SCORE_RULE_ID
     *
     * @mbggenerated
     */
    private BigDecimal scoreRuleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCORE_RULE.SURVEY_MOUDLE_ID
     *
     * @mbggenerated
     */
    private BigDecimal surveyMoudleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCORE_RULE.SCORE_RULE_TITLE
     *
     * @mbggenerated
     */
    private String scoreRuleTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCORE_RULE.FORMULA
     *
     * @mbggenerated
     */
    private String formula;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCORE_RULE.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCORE_RULE.OP_TIME
     *
     * @mbggenerated
     */
    private Date opTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCORE_RULE.OPERATOR
     *
     * @mbggenerated
     */
    private BigDecimal operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCORE_RULE.SCORE_RULE_ID
     *
     * @return the value of SCORE_RULE.SCORE_RULE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getScoreRuleId() {
        return scoreRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCORE_RULE.SCORE_RULE_ID
     *
     * @param scoreRuleId the value for SCORE_RULE.SCORE_RULE_ID
     *
     * @mbggenerated
     */
    public void setScoreRuleId(BigDecimal scoreRuleId) {
        this.scoreRuleId = scoreRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCORE_RULE.SURVEY_MOUDLE_ID
     *
     * @return the value of SCORE_RULE.SURVEY_MOUDLE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getSurveyMoudleId() {
        return surveyMoudleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCORE_RULE.SURVEY_MOUDLE_ID
     *
     * @param surveyMoudleId the value for SCORE_RULE.SURVEY_MOUDLE_ID
     *
     * @mbggenerated
     */
    public void setSurveyMoudleId(BigDecimal surveyMoudleId) {
        this.surveyMoudleId = surveyMoudleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCORE_RULE.SCORE_RULE_TITLE
     *
     * @return the value of SCORE_RULE.SCORE_RULE_TITLE
     *
     * @mbggenerated
     */
    public String getScoreRuleTitle() {
        return scoreRuleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCORE_RULE.SCORE_RULE_TITLE
     *
     * @param scoreRuleTitle the value for SCORE_RULE.SCORE_RULE_TITLE
     *
     * @mbggenerated
     */
    public void setScoreRuleTitle(String scoreRuleTitle) {
        this.scoreRuleTitle = scoreRuleTitle == null ? null : scoreRuleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCORE_RULE.FORMULA
     *
     * @return the value of SCORE_RULE.FORMULA
     *
     * @mbggenerated
     */
    public String getFormula() {
        return formula;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCORE_RULE.FORMULA
     *
     * @param formula the value for SCORE_RULE.FORMULA
     *
     * @mbggenerated
     */
    public void setFormula(String formula) {
        this.formula = formula == null ? null : formula.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCORE_RULE.CREATE_TIME
     *
     * @return the value of SCORE_RULE.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCORE_RULE.CREATE_TIME
     *
     * @param createTime the value for SCORE_RULE.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCORE_RULE.OP_TIME
     *
     * @return the value of SCORE_RULE.OP_TIME
     *
     * @mbggenerated
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCORE_RULE.OP_TIME
     *
     * @param opTime the value for SCORE_RULE.OP_TIME
     *
     * @mbggenerated
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCORE_RULE.OPERATOR
     *
     * @return the value of SCORE_RULE.OPERATOR
     *
     * @mbggenerated
     */
    public BigDecimal getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCORE_RULE.OPERATOR
     *
     * @param operator the value for SCORE_RULE.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(BigDecimal operator) {
        this.operator = operator;
    }
}