package com.unique.survey.po;

import java.math.BigDecimal;

public class SurveyEvaluate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SURVEY_EVALUATE.SE_ID
     *
     * @mbggenerated
     */
    private BigDecimal seId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SURVEY_EVALUATE.SURVEY_ID
     *
     * @mbggenerated
     */
    private BigDecimal surveyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SURVEY_EVALUATE.EVALUATE_RULE_ID
     *
     * @mbggenerated
     */
    private BigDecimal evaluateRuleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SURVEY_EVALUATE.SE_ID
     *
     * @return the value of SURVEY_EVALUATE.SE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getSeId() {
        return seId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SURVEY_EVALUATE.SE_ID
     *
     * @param seId the value for SURVEY_EVALUATE.SE_ID
     *
     * @mbggenerated
     */
    public void setSeId(BigDecimal seId) {
        this.seId = seId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SURVEY_EVALUATE.SURVEY_ID
     *
     * @return the value of SURVEY_EVALUATE.SURVEY_ID
     *
     * @mbggenerated
     */
    public BigDecimal getSurveyId() {
        return surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SURVEY_EVALUATE.SURVEY_ID
     *
     * @param surveyId the value for SURVEY_EVALUATE.SURVEY_ID
     *
     * @mbggenerated
     */
    public void setSurveyId(BigDecimal surveyId) {
        this.surveyId = surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SURVEY_EVALUATE.EVALUATE_RULE_ID
     *
     * @return the value of SURVEY_EVALUATE.EVALUATE_RULE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getEvaluateRuleId() {
        return evaluateRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SURVEY_EVALUATE.EVALUATE_RULE_ID
     *
     * @param evaluateRuleId the value for SURVEY_EVALUATE.EVALUATE_RULE_ID
     *
     * @mbggenerated
     */
    public void setEvaluateRuleId(BigDecimal evaluateRuleId) {
        this.evaluateRuleId = evaluateRuleId;
    }
}